### ISSUE TITLE
ALIS usability – automatic wildcards

### ISSUE THREAD

**Issue by grawity** [atheme/atheme#193]
Using ALIS `LIST` with an exact channel name makes little sense as the user can get the same with `/list` and/or `/topic`, and it is practically impossible to use `LIST * -topic …` with an exact topic name. On the other hand, many users apparently don't realize that the `*`'s in examples are actual wildcards, not example delimiters.

Suggestion: Automatically surround the "channel" and "topic" arguments with `*` wildcards (e.g. `-topic foo` → `-topic *foo*`), *unless* they already have at least one wildcard character (`-topic foo*` remains untouched).

**Comment by ilbelkyr** [comment]
Looks like this has been addressed in 0831bb5, 4bf22e7, and a few other commits, so this issue can probably be closed.
