### ISSUE TITLE
Installation error: Cannot stat es.mo: No such file or directory

### ISSUE THREAD

**Issue by Arkadietz** [atheme/atheme#247]
Install: dbverify
Install: ecdsakeygen
Install: es.mo
/usr/bin/install: cannot stat `es.mo': No such file or directory
make[1]: **\* [install] Error 1
make: **\* [install] Error 2

**Comment by manavortex** [comment]
Thanks, ran into this problem too.

**Comment by aaronmdjones** [comment]
On Debian systems and their derivatives, this is usually the package named `libgettextpo-dev`. The `php-gettext` package may well depend on that package.

**Comment by manavortex** [comment]
Nice to know, thanks :)
