### ISSUE TITLE
serno.h generation step requires a github repo

### ISSUE THREAD

**Issue by rjhornsby** [atheme/atheme#382]
In include/Makefile, line 70

```
@revh=`git log -1 --pretty=oneline | cut -d' ' -f1 2>/dev/null` || :; \
[ -z "$$revh" ] || echo "#define SERNO \"$$revh\"" >serno.h
```

causes the compile to fail unless the code was checked out from github.  Download the tarball from the atheme website and try to compile from will fail because of this line.  The issue shows itself this way during the compile:

```
$ make
Generate: hooktypes.h
Generate: serno.h
fatal: Not a git repository (or any parent up to mount point /some/path)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
...
version.c:9:10: fatal error: 'serno.h' file not found
#include "serno.h"
         ^
1 error generated.
make[1]: *** [version.lib.o] Error 1
make: *** [libathemecore] Error 2
```

Unfortunately, it isn't clear (that I've been able to find) what string value SERNO should be other than the commit hash, or what it is used for so I'm not sure how to generate one correctly without being able to call `git log`.  It appears that this issue can be bypassed to successfully compile by creating a serno.h file with a string value of "0".

`#define SERNO "0"`

**Comment by GenBurnside** [comment]
I'm getting this same error on version 7.2.6. I downloaded the tarball and extracted it, and there is no ``serno.h`` in the ``include`` directory.

**Comment by aji** [comment]
chances are the person who prepared that release didn't use the `makerelease.sh` script or whatever it's called, someone with access should remedy this (and check that tarballs build after being extracted)

**Comment by kaniini** [comment]
not true, he downloaded a github tarball.  i wish you could turn that bullshit off.

**Comment by Mikaela** [comment]
>  i wish you could turn that bullshit off.

Request that from GitHub support. Maybe they will implement it when enough people complain.

I contacted them with ZNC where tar/zipballs are broken due to it also using submodules.

**Comment by GenBurnside** [comment]
I was able to work around this issue by copying the serno.h file from the charybdis include directory (charybdis-3.4.2) into atheme's include directory.
