### ISSUE TITLE
EXTTARGETS can have +F

### ISSUE THREAD

**Issue by Mikaela** [atheme/atheme#427]
This probably doesn't make sense as hostmasks cannot have +F either and the only sane exttarget would be `$oper`, but at IRC it was said that `$oper` can give access to unexpected people and making group `!netadmins` is better idea. There is also `regnolimit` command in GroupServ.

*This issue was renamed and rewritten 2015-01-10 23:20+0200.*

**Comment by Mikaela** [comment]
Or could there even be `$soper` (possibly only settable by sopers`) which overrides the limit?

**Comment by GLolol** [comment]
FYI the same thing can be done with other exttargets: setting them as founder. This works with `$oper`, `$registered`, `$server`, and more.

**Comment by Mikaela** [comment]
I think that Shalture's translations said that hostmasks canot be founders and this should probably also affect exttargets so this is a bug.

**Comment by GLolol** [comment]
I agree... I've noticed it before but never remembered to report it.

**Comment by kaniini** [comment]
This shouldn't be working.  exttarget's `can_register_channel` function returns `false`.

**Comment by Mikaela** [comment]
> `2015-02-09 17:42:41+0200 -- ChanServ: Flags +Ff were set on $oper in #english.`
> `2015-02-09 17:42:57+0200 -- CTCP reply from ChanServ: VERSION atheme 7.2.5. services.queertech.irc 23c44de17b64cd4a1d803f51e2895d3152fbdb7c :cFljR [InspIRCd] [enc:posix] Build Date: Feb  3 2015`

works well here

**Comment by maxteufel** [comment]
Then something [here](https://github.com/atheme/atheme/blob/master/modules/exttarget/oper.c#L37-L40) or [here](https://github.com/atheme/atheme/blob/master/modules/exttarget/oper.c#L45) is broken.

**Comment by kaniini** [comment]
Alternately it could mean that enforcement of +F in FLAGS is incorrect.

**Comment by spb** [comment]
Unfortunately the fix for this broke channel registration for normal users, and the logic inversion which did so also made existing functionality (users being exempt from registration limits) impossible to fix. A more thorough fix is needed for this issue.
