### ISSUE TITLE
Add configurable expiry time for unverified NickServ accounts

### ISSUE THREAD

**Issue by Renegade334** [atheme/atheme#429]
Currently, the time that users get to verify their NickServ accounts (if e-mail verification is enabled) is hard-coded at 1 day. Would be better as a configurable option, with some way of specifying minutes/hours/days for the NickServ REGISTER message.

Possibly a post-atheme feature.

**Comment by jillest** [comment]
Do you have any rationale? Just because something can be made configurable doesn't mean it's a good idea. Also, this hard-coded time has existed for quite a while without complaints.

**Comment by Renegade334** [comment]
The rationale for our environment is pretty specific, admittedly, so feel free to close as WONTFIX if it's not worth changing.
