### ISSUE TITLE
Missing ban exemption (+e) condition is causing a rare regain issue

### ISSUE THREAD

**Issue by soulseller** [atheme/atheme#433]
The lines `324-325` of `enforce.c` are missing a case when a given hostname has been banned from a channel, but a specific user with the same hostname has been added to the exemption/exception list. This is causing the user to see an unexpected message from NickServ `You can not regain your nickname while banned or quieted on a channel.` while trying to unsuccessfully regain its nickname.

**Comment by ilbelkyr** [comment]
I think NickServ REGAIN is generally a bit overly strict.

For reference, see shalture/shalture@8bd76b1, shalture/shalture@cd98a67, shalture/shalture@77edeaf and possibly shalture/shalture@fb5b7e9.

**Comment by kaniini** [comment]
I merged those commits which should fix this issue.

**Comment by a-raccoon** [comment]
I think REGAIN also doesn't take into account bans and quiets of the mask $~a.  The user is unidentified at the time they use REGAIN, so they provide their account password to REGAIN for the purpose of becoming identified.  $~a says they are banned/quieted in their current unidentified state, and so REGAIN fails.

Perhaps add an exception for $~a masks if password is given, or at least identify the user first before failing REGAIN.
