### ISSUE TITLE
Inconsistencies with setting ChanServ founders

### ISSUE THREAD

**Issue by Renegade334** [atheme/atheme#439]
* Restricted or unverified users are not permitted from registering channels; however, they can get another user to register the channel, then transfer foundership using `SET FOUNDER` or `FLAGS +F`, both of which allow restricted or unverified users to receive foundership.
* The source comments for `SET FOUNDER` indicate that the two-step verification process exists to avoid innocent users from having "bad" channels transferred into their name without their consent. However, a malicious user can use `FLAGS InnocentUser +F*` and then delete themselves from the access list, which mimics `SET FOUNDER` but without the verification step.

**Comment by kaniini** [comment]
Unfortunately I think the easy way to fix this is just to remove the two-step on `SET FOUNDER` since it silently broke with multi-founder options years ago.

**Comment by Renegade334** [comment]
Or, indeed, removing `SET FOUNDER` entirely, since it's only really logically consistent with a single-founder system.

**Comment by kaniini** [comment]
Yep.  I agree.  I'll nuke it in the morning.

**Comment by MrBenC** [comment]
Perhaps additional checks should be added to prevent setting +F on restricted or unverified users.

**Comment by kaniini** [comment]
The decision has already been made to just nuke it.

**Comment by Renegade334** [comment]
I think the reference was to `FLAGS` rather than `SET FOUNDER`.

**Comment by MrBenC** [comment]
Correct.  ``/cs flags #Channel TargetUser +F`` should probably only work if TargetUser is verified and not restricted.  This has nothing to do with retaining, or not retaining the ``SET FOUNDER`` command.

**Comment by Renegade334** [comment]
Edge case: what should happen if a restricted user is on a channel's access list, the founder's NickServ account expires, and the user is either *a)* the only remaining entity on the channel access list; or *b)* not the only remaining entity, but would be selected by the successor algorithm?

Also, there's nothing to stop a restricted user from being part of a GroupServ group that gets the founder flag on a channel, although it's pretty hard to see an easy way around that. That said, registering GroupServ groups should probably be another action that restricted/unverified users can't do.

**Comment by MrBenC** [comment]
In that particular edge case, I would say the channel should simply be dropped (if the only other ACL entry) or skipped to the next one (if other eligible ACL entries exist).

Agreed on the GroupServ restrictions; restricted and/or unverified users should not be able to do any of those things.

**Comment by Mikaela** [comment]
Isn't this fixed by https://github.com/atheme/atheme/commit/d8acb0b663e3cad4a09e9cd25ba26280c017e3f8 ?

**Comment by B00mX0r** [comment]
Yes

**Comment by kaniini** [comment]
I am keeping it open for the other aspect brought up by @MrBenC since GitHub issues is hopeless and doesn't allow splitting.

**Comment by kaniini** [comment]
I think the solution here is to apply restriction to taking `+F` by adding code to handle it into the default validation function for taking `+F`.  Thoughts?

**Comment by Renegade334** [comment]
@kaniini, should there be a more intimite relationship between `myentity_can_register_channel` and `myentity_allow_foundership`? The semantics of the two are more or less identical, and `myentity_can_register_channel` is already used for applications like foundership succession in `mychan_pick_candidate`.

**Comment by kaniini** [comment]
@Renegade334 not really, they have two purposes.  one describes if an entity is capable of channel registration, and the other describes if it is capable of taking ownership.  an entity can be a founder without being able to register, consider groups for example.
