### ISSUE TITLE
Handling of GroupServ groups when the last founder is dropped/expired

### ISSUE THREAD

**Issue by Renegade334** [atheme/atheme#443]
Currently, groups are left founderless (and potentially without any groupacs entries whatsoever) if the last founder is dropped/expired. Either the group should be deleted, or there should be some sort of succession procedure à la ChanServ.

As things stand, this would have to be handled by a hook within the GroupServ module itself, rather than as part of the `myuser_delete` destructor in `libathemecore/account.c`, due to the inaccessibility of groups functions outside the GroupServ module. My personal viewpoint is that it's time to consider integrating the "core" groups headers and functions into libathemecore: the feature is now relatively mature, and processes like this one could be implemented in a way that is more consistent with other areas of Atheme. Food for thought, perhaps.

**Comment by kaniini** [comment]
We will not be making these kinds of intensive changes to Atheme since it is EOL in May.  Perhaps it would be worthwhile to consult a downstream fork such as Shalture?

**Comment by Renegade334** [comment]
I agree with respect to the latter half, but the core issue seemed to be suitable for addressing within Atheme - I would consider leaving groups without any member having access to configure the group as a bugfix rather than an enhancement. However, will raise downstream.

**Comment by Mikaela** [comment]
Is this fixed or should this be reopened?
