### ISSUE TITLE
CS SET SECURE ignores +qa on channel

### ISSUE THREAD

**Issue by Mikaela** [atheme/atheme#449]
I am not sure if this is just us, but I can use `/mode +qa person1 person2` without SECURE setting the opposite mode. `+ho` get unset automatically. If I use `/cs protect #channel person` I get error message about person not having required access.

* atheme 7.2.5
* InspIRCd-2.0.18

**Comment by dboyz** [comment]
Hi. I am able to duplicate this on atheme 7.1.0. I am unsure what version of Inspircd is used though. (I do not have oper access)

**Comment by GLolol** [comment]
@dboyz `/raw version` should tell you (no oper needed).

**Comment by Mikaela** [comment]
@GLolol InspIRCd hides the full version from other users than opers. It might tell you major version or something.

> `2015-02-08 20:15:43+0200 < DBoyz> it still displays InspIRCd-2.0`

**Comment by GLolol** [comment]
(well at least we know 2.0 is being used and not some ancient version)

Which module is being used to handle `+qa`? `m_chanprotect` or `m_customprefix`? You might be able to find out by doing `/modules`.

**Comment by Mikaela** [comment]
Oh, I forgot to say that. `m_customprefix` for our network, no idea on @dboyz .

CC: @Annwenn

**Comment by dboyz** [comment]
m_chanprotect for this network I am testing on.

**Comment by Mikaela** [comment]
at IRC @dboyz said that they think that the issue might be in inspircd protocol module. I also said this on \#inspircd, but I am not sure if anyone noticed and all information should probably be in this issue.
