### ISSUE TITLE
Show last-success upon identifying

### ISSUE THREAD

**Issue by Gryllida** [atheme/atheme#454]
Upon successfully identifying, Atheme notifies users about number of failed identify attempts, and hostmask of the last such failed identify attempt. However, no information about last _successful_ identify attempt is shown. The only way for users to know that their account was compromised is either by
- noticing that the password changed, or
- running an INFO command before each IDENTIFY command by hand.

This situation leaves users unaware of successful account issues which did not involve password changes.

There should be some means for the user to know where (at least one) successful identify attempt is from. This should be information about either
- 1 last successful identify hostmask, or
- a list of several last hostmasks the user identified from (like Gmail, screenshot included)

![Last activity screenshot](http://3.bp.blogspot.com/_ZaGO7GjCqAI/SHKTZEbytHI/AAAAAAAAJk4/biD2JqBT8FU/s640/gmail-sessions.png)

Obviously this information may be annoying to many people who have no issues. To avoid surprises, it may need to be opt-in (or opt-out), or be viewable through a "/msg nickserv LASTLOGINS" command.

**Comment by Mikaela** [comment]
:+1:

> * 1 last successful identify hostmask, or
> * a list of several last hostmasks the user identified from (like Gmail, screenshot included)

I think that the first should be shown always and the second could be behind separate command.

> To avoid surprises, it may need to be opt-in (or opt-out).

I think opt-out would be better.

**Comment by siniStar7boy** [comment]
Added in a9e770013e9a4fe21c37f1063bfff828d267e782

**Comment by Zarthus** [comment]
While I think the change is good, I think the feature (as is) can be improved upon by allowing opting (in|out), as well as only notifying you (or changing the message when) the host was different from your current one.

While the value of the latter suggestion loses value for dynamic IPs and those logging in from multiple devices, those with a single connection on a static host will benefit from it. Which is still a portion of the userbase, and would allow for easier filtering of certain messages (basically implementing the former suggestion, client-side.)

I'd imagine the notice will also be easily missed, as I often barely notice the "You need to log in to this account ..." from NickServ/ENFORCE. So the former suggestion isn't top-priority, but I would definitely be filtering it out personally for my current hostname.

**Comment by siniStar7boy** [comment]
Thanks for the input - those are **helpful** ideas.

Since this is meant to _improve security (or at least visibility)_, I personally think it should indeed be something that a user _can_ **opt-out** of -- but I feel it should be enabled by default.  I will take another look at this tonight.

Additional comments/feedback are welcome.

**Comment by siniStar7boy** [comment]
Fixed in b3c8dff6e6bd50d1e088b662daa8a97872813068 (Users can now opt-out, if they wish)
