### ISSUE TITLE
HostServ access {} bug with activate.

### ISSUE THREAD

**Issue by deathspawn** [atheme/atheme#459]
So if you deny access to the VHOST command using the access {} block, but give someone the user:vhost privilege, if that person tries to activate a requested vhost, they will get a permission error, however, the command will still work. The vhost will be approved and the memo will go out as intended.

**Comment by kaniini** [comment]
Please provide example configuration.

**Comment by deathspawn** [comment]
```C
hostserv {
        access {
                "VHOST" = "crush:hostserv:vhost";
        };
};

operclass "test" {
        privs {
                user:vhost;
        };
        needoper;
};
```

**Comment by kaniini** [comment]
And the user is really in the `test` operclass context?

**Comment by deathspawn** [comment]
Sorry for the delayed response. Yes, they are in the test operclass. I added them via Operserv's Soper command, if that makes any difference. The intended outcome is to not get hit with a permissions error upon executing activate, but to still leave the vhost command disabled. (So they can accept requested vhosts, but not manually set them.)

**Comment by kaniini** [comment]
That isn't possible that way, you'll need to write a custom security module.
