### ISSUE TITLE
CS CLONE copies oper only flags such as 'hold' and 'antiflood akill'

### ISSUE THREAD

**Issue by shaynejellesma** [atheme/atheme#462]
Using CS CLONE to clone a channel results in oper only channel flags also being copied over to the new channel such as 'hold' and 'antiflood akill'

**Comment by siniStar7boy** [comment]
I don't believe it should _(personally)_ clone the *HOLD* over to the new channel, as that would bypass it's normal expiration checks and should only _(again, in my opinion)_ be manually decided by network staff.  

However, as far as ANTIFLOOD, that can be changed by the target channel without necessarily being a Services Operator.  _(So in theory, it *should* clone ANTIFLOOD's action/settings)_

**Comment by siniStar7boy** [comment]
Further discussion on IRC seems to disagree as far as *ANTIFLOOD AKILL*.  Thus, *ANTIFLOOD AKILL* should also not be cloned.  Coming in a PR or commit soon.

Also, *MARK* information should not be cloned as well, as pointed out by @shaynejellesma

**Comment by kaniini** [comment]
I think MARK information should be cloned if the person doing the clone is a user.  Because the person may move the channel to evade the MARK.

**Comment by MrBenC** [comment]
If MARK'd channels are blocked from cloning, that could possibly tip off the user, which could partially defeat the purpose.  So no, MARK'd channels should not be blocked from cloning.

Ben
