### ISSUE TITLE
CS KICK ignores CMODE_IMMUNE

### ISSUE THREAD

**Issue by shaynejellesma** [atheme/atheme#463]
CS KICK ignores the CMODE_IMMUNE flag in the IRCd's protocol (atleast for InspIRCd) and allows users to kick users who should be immune to kicks.

**Comment by shaynejellesma** [comment]
I looked into this a little more. This is what I believe is happening, but I by no means fully understand how Atheme works under the hood.


It seems that Atheme is tracking the +Y mode incorrectly.
The +Y mode works more than a CSTATUS (+o, +v) than a CMODE (+m, +n) and is assigned to a specific user.

Currently it appears that if anyone is +Y on a channel, Atheme will treat all opers as immune.

We have also seen ChanServ kick an oper immediately on join, even if they are OJOIN'ing.

[02-Apr|20:14:22] == JOIN Rick (Rick!Rick@staff/xx) has joined #Rick2
[02-Apr|20:14:22] * dart.xx sets mode: +Y Rick
[02-Apr|20:14:22] -dart.xx:#Rick2- Rick joined on official network business.
[02-Apr|20:14:22] * ChanServ sets mode: +b *!*@staff/xx
[02-Apr|20:14:22] * Rick was kicked by ChanServ (Banned: test)

**Comment by kaniini** [comment]
Atheme does not track `+Y` because it does not grant the "immunity" you describe, it is purely cosmetic.
