### ISSUE TITLE
"/cs why" can reveal arbitrary cloaked user ips

### ISSUE THREAD

**Issue by j4g3r** [atheme/atheme#468]
attack can be mounted by registering a channel then using cs why: if you add 127.0.* to your channel's access list and check whether I match that using CS WHY, if I do, narrow it down by halves until you find that i'm on 127.0.0.1, etc. while it is understood that cloaks do not provide true anonymity this still seems like a situation that could be improved or mitigated. thanks in advance :)

**Comment by j4g3r** [comment]
one suggested fix might be to send notices to affected users. another might be to rate limit cs why. thanks again!

**Comment by Mikaela** [comment]
Cloaks aren't meant to provide whole anonymity and there are many ways to go through them.

* [Security of unaffiliated cloaks at freenode](https://gist.github.com/maxteufel/1e2cf7ada079c271bd3c)
* [Uncloaking IP-addresses in IRC (PDF)](http://decal.sdf.org/spotfedsonline/Uncloaking-IP-Addresses-on-IRC.pdf)

As the links above show, there are many other ways to see through cloaks and Atheme cannot do anything to it as it would remove functionality. Anope again is interested in keeping cloaks fully anonymous and removing features which would be important. *(Note to self: https://github.com/Mikaela/mikaela.github.io/issues/45)*

**Comment by kaniini** [comment]
Not a bug.
