### ISSUE TITLE
Send Group Memos for HostServ Requests

### ISSUE THREAD

**Issue by Casey952** [atheme/atheme#474]
From Xtheme

To be notified of new HostServ requests

**Comment by siniStar7boy** [comment]
:+1:  

(This might be added in the _new features_ release.. _[7.3+]_ -- Reference/more details can be found at: https://github.com/XthemeOrg/Xtheme/commit/d28de2eaeddefbb9311ed584c5b99689a70ba59f)

**Comment by siniStar7boy** [comment]
Added in commit a8aa874d7c57e71b7834b09a40c559c814dbfb1b
