### ISSUE TITLE
Atheme not setting +r on identified users

### ISSUE THREAD

**Issue by ripnet** [atheme/atheme#485]
Using inspircd. Any ideas?

**Comment by GLolol** [comment]
AFAIK `+r` isn't used on InspIRCd because there's no use for it. InspIRCd can tell whether someone is logged in by simply checking for their account name. Only on IRCds on Unreal does `+r` actually matter (for things like `+R` channels).

**Comment by ripnet** [comment]
So how do I tell if a user is identified, and how do I do a +R channel on inspircd?

**Comment by GLolol** [comment]
You whois them. There'll be a line in the form of `X is logged in as Y` (account name and nick don't need to necessarily match).

`+R` channels are accounted for by the IRCd, just by checking for account names.

**Comment by ripnet** [comment]
I don't see that in any whois I've done, on users that I know are logged in. Maybe I'm missing a module?

**Comment by GLolol** [comment]
You *have* to load `m_services_account.so`. This is documented at https://github.com/atheme/atheme/blob/master/doc/IRCD#L48

**Comment by ripnet** [comment]
That is definitely loaded.

**Comment by ripnet** [comment]
Turns out this is my irssi client not displaying it. I used another client and it's there. Thanks for the help @GLolol
