### ISSUE TITLE
--enable-contrib build fails with nontelling error message

### ISSUE THREAD

**Issue by jengelh** [atheme/atheme#489]
```
abuild@ares40:/home/abuild/rpmbuild/BUILD/atheme-atheme-7.2.6> make
[...]
CompileLib: version.lib.o
Link: libathemecore.so
CompileModule: version.so
make[2]: *** No targets.  Stop.
../buildsys.mk:120: recipe for target 'contrib' failed
make[1]: *** [contrib] Error 2
buildsys.mk:120: recipe for target 'modules' failed
make: *** [modules] Error 2
```
This happens when configuring with `--enable-contrib`, as there is no longer a `contrib/Makefile` provided.

**Comment by maxteufel** [comment]
Where and why would a makefile be expected in the `contrib/` subdirectory? `--enable-contrib` enables building contrib modules in `modules/contrib/`, where a makefile exists (in the git submodule and in the tarball).

**Comment by kaniini** [comment]
Why are you building from github sources instead of official sources at http://atheme.github.io/?  The github tarballs are incomplete due to use of submodules etc.

**Comment by siniStar7boy** [comment]
Please either use git, or build from the official sources at https://atheme.github.io/  As mentioned, the GitHub downloads are incomplete due to use of submodules, etc.
