### ISSUE TITLE
ChanServ does not rejoin all channels upon an IRCd reboot.

### ISSUE THREAD

**Issue by vinniemac** [atheme/atheme#49]
I have found a problem that seems to be Atheme specific where by if an IRCd is restarted or the process is killed, upon startup ChanServ will not rejoin all the channels thus making them unavailable in a /list until someone physically rejoins them all to make ChanServ then join.

I have found this behaviour using Atheme7.0.4 and Unreal3.2.9 and on ShadowIRCd6.3.2.1 and Charybdis3.3.0

Is there any way of changing the behaviour so ChanServ can join all channels upon a server reboot?
 I know ways around it can be setting a bot to join them all in order for ChanServ to join but this is not really feasable.
 Also join chans is set in the Atheme configuration.

Best Wishes

Vince

**Comment by dosomder** [comment]
I have a use case for this. I have disabled `chanserv::leave_chans` and I need ChanServ to join all registered channels when the services start.

It's not a problem for me to program this. I am wondering though if a PR for that would be welcome or not?
