### ISSUE TITLE
OperServ SPECS lists user:mark twice

### ISSUE THREAD

**Issue by Brand3n** [atheme/atheme#490]
/msg OperServ SPECS username shows this
-OperServ- Privileges for username
-OperServ- Nicknames/Accounts:
-OperServ-     user:auspex (view concealed information about accounts)
-OperServ-     user:admin (drop accounts, freeze accounts, reset passwords)
-OperServ-     user:sendpass (send passwords)
-OperServ-     user:vhost (set vhosts)
**-OperServ-     user:mark (mark accounts)**
-OperServ- Channels:
-OperServ-     chan:auspex (view concealed information about channels)
-OperServ-     chan:admin (drop channels, close channels, transfer ownership)
-OperServ-     chan:cmodes (mlock operator modes)
-OperServ-     chan:joinstaffonly (join staff channels)
**-OperServ-     user:mark (mark accounts)**
[..........]

The user has the settings from the 'ircop' operclass, which is not changed from the default, and is:
operclass "ircop" {
	privs {
		special:ircop;
	};
	privs {
		user:auspex;
		user:admin;
		user:sendpass;
		user:vhost;
		user:mark;
	};
	privs {
		chan:auspex;
		chan:admin;
		chan:cmodes;
		chan:joinstaffonly;
	};
	privs {
		general:auspex;
		general:helper;
		general:viewprivs;
		general:flood;
	};
	privs {
		operserv:omode;
		operserv:akill;
		operserv:jupe;
		operserv:global;
	};
	privs {
		group:auspex;
		group:admin;
	};
};

Atheme 7.2.6

**Comment by siniStar7boy** [comment]
The second mention should be clear to mention the ability to mark _channels_, since the privilege to mark accounts/channels is one and the same.  I'll fix this in a few minutes.
