### ISSUE TITLE
Backport fixes from Shalture

### ISSUE THREAD

**Issue by maxteufel** [atheme/atheme#491]
Fixes and minor improves from [shalture/shalture](https://github.com/shalture/shalture) that haven't been imported should be included in a minor 7.2 release, be it 7.2.7 or 7.2.8.

**Comment by GLolol** [comment]
Is there a list of which patches are of interest? From all the cherry-picking it's becoming hard to trace the origin of each commit.

**Comment by maxteufel** [comment]
@GLolol well at first someone would have to go through all shalture commits to find out what's worth including in 7.2.z (since it's a bugfix release, only bugfixes should be added).

**Comment by maxteufel** [comment]
This seems to be done.
