### ISSUE TITLE
chanserv improvement request: filter access list for flags

### ISSUE THREAD

**Issue by Joerg-rw** [atheme/atheme#493]
chanserv syntax:  ACCESS <#channel> LIST [flags-filter]    

Example  
/msg chanserv access #freenode list +o

to list all +o access list records only

-o to list all records that do _not_ have +o. 

Combinations of filters should get supported too: +F-o.  Maybe even allow OR, like '+o,+b'  for all records that have +o, or +b, or both

**Comment by kaniini** [comment]
The ACCESS command used on freenode is not the one shipped in atheme.  You will need to ask them for this improvement.
