### ISSUE TITLE
Issue installing using GitHub release

### ISSUE THREAD

**Issue by alex-jch** [atheme/atheme#496]
I downloaded the latest release at https://github.com/atheme/atheme/archive/atheme-7.2.6.tar.gz.

Once extracted I tried to run `./configure` but it said that I needed to read `GIT-Access` and run some `git` commands, even though I am not using the `git` version so it's impossible.

I ended up downloading the latest `.bz2` from the Atheme website and it installed fine.

**Comment by siniStar7boy** [comment]
That is why we do not recommend using the Download button on GitHub, but rather download the package at https://atheme.github.io/

**Comment by GLolol** [comment]
FYI, seeing that this isn't the first time this error has happened, I think this case should be better documented.

**Comment by kaniini** [comment]
Or better yet, maybe github should let people disable the feature :/

**Comment by alex-jch** [comment]
@siniStar7boy I was not talking about the green 'Download' button on the projects home page on GitHub. I was talking about the list of available releases at https://github.com/atheme/atheme/releases. This is where I usually download any software from, like InspIRCd etc. (that works).

**Comment by GLolol** [comment]
Those aren't the official release downloads atheme uses - https://atheme.github.io/ IS.

**Comment by kaniini** [comment]
@alex-jch the releases tab still does a git checkout that is incomplete.  as i've said before, it'd be nice to have the ability to disable this feature at github :/

**Comment by maxteufel** [comment]
@kaniini You can actually add custom downloads for tags: <https://github.com/atheme/atheme/releases/new>

**Comment by kaniini** [comment]
Yes, but it doesn't remove the download option for the git repository.
