### ISSUE TITLE
OperServ issue when using override

### ISSUE THREAD

**Issue by Brand3n** [atheme/atheme#497]
When trying to use OperServ OVERRIDE with a global notice, it gives a permissions error, even though myself and the person I try to override has appropriate privileges.

Here is the command: /os override other-oper OperServ GLOBAL This is a message

Here is what I get:
<OperServ> Brand3n OVERRIDE: (account: other-oper) (service: OperServ) (command: GLOBAL) [parameters: This is a message]
<OperServ> DENYCMD: Brand3n/other-oper/vhost was denied execution of GLOBAL, need privileges operserv:global operserv:global
-OperServ- You do not have the operserv:global privilege.

~~Notice that on the DENYCMD line, it has my nick, the other oper's nick, but then it just says 'vhost' which is not my or the other oper's actual vhost. I don't know if that has to do with the permissions error, but it is something strange as well.~~ Ignore that. 'vhost' is the operclass of other-oper

**Comment by Dessa** [comment]
override should use the target privs so this is likely no bug.
vhost is what the operclass of the target is called (because i gave it user:vhost only)

**Comment by Brand3n** [comment]
The target has the correct privs (operserv:global) inherited from the atheme default ircop class, since they are an oper on the IRCd

**Comment by siniStar7boy** [comment]
@Brand3n Do you also have the `operserv:global` privilege?  **Also**, are you sure _(if required by your SOPER class)_ /oper'd up and identified?

**Comment by Brand3n** [comment]
@siniStar7boy Yes, I have the required privileges (operserv:override and operserv:global in this case). I am also identified to NickServ, and oper'd on the IRCd. In addition, the other-oper was also identified to NickServ and /oper'd when I got the permissions error.

**Comment by kaniini** [comment]
The target in this case has to do with an account, not with a specific user on the network.  If a user gains his privileges through a dynamic attribute (such as being opered), then the override will not gain those privileges.
