### ISSUE TITLE
hostserv check requests for duplicate

### ISSUE THREAD

**Issue by TurkDesk** [atheme/atheme#498]
hostserv request should be checked if another account has the vhost and if so
maybe something like: the vhost u request is taken by another user, please try another one or see an oper. for reject msg would solve issues like someone trying get others in troubles, helpchan from config may also be used in the msg as well.

**Comment by maxteufel** [comment]
This is network policy and should be a configuration option.

**Comment by siniStar7boy** [comment]
It is _almost_ ready for Atheme then, will need to modify current code to allow config options to turn on/off this functionality. _(Sometime this week)_  Functionality will be enabled by default, however.

**Comment by siniStar7boy** [comment]
Fixed in 6a4e22a9ad5cbd5eaba6d373b78f5502212b92d0 and 35c869199075dec91b6e463dd8d6ced49126d2c4.  Configurable option coming soon.
