### ISSUE TITLE
ChanServ: FANTASY flag

### ISSUE THREAD

**Issue by Xenthys** [atheme/atheme#503]
Hello,

I'd like to talk about a possible improvement that could be made.
When you enable a module such as chanserv/set_fantasy, all channels will have the FANTASY flag by default. As it's not treated like any other flag, even if you don't put it in cflags it WILL be enabled.

The mean I found to disable the fantasy mode by default is to add a metadata.

```
metadata_add(mc, "disable_fantasy", "on");
```

This piece of code in chanserv/register should work.

However, it would be more user friendly to at least have an option in the config file and/or through the OS SET command to tell if this flag should (or not) be enabled by default.

**Comment by kaniini** [comment]
The use of metadata for this seems inefficient.  I wonder if atheme should make use of charybdis's dynamic capabilities code to allocate capability bits as needed.

**Comment by Xenthys** [comment]
Right now, that's the only workaround I managed to find.
Changing that system means rewriting a lot of code, not sure if that's a priority right now.
