### ISSUE TITLE
Unicode channel register

### ISSUE THREAD

**Issue by Doemela** [atheme/atheme#505]
I have a users that registered channels with Unicode Character 'ZERO WIDTH NON-JOINER' (U+200C) an Unicode Character 'RIGHT-TO-LEFT OVERRIDE' (U+202E)
People can do /ns #chan ctrl+alt+u 200c space
This creates channels that look like other registered channels with same name because ppl wont see the Unicode behind chan name

Channel registered by me:
-> *ChanServ* INFO #kill
-ChanServ- Information on #kill:
-ChanServ- Founder    : Doemela, RedAcor
-ChanServ- Successor  : vhost
-ChanServ- Registered : Feb 08 17:34:57 2015 +0100 (1y 25w 4d ago)
-ChanServ- Mode lock  : +ntCu-lk
-ChanServ- Flags      : SECURE KEEPTOPIC TOPICLOCK FANTASY PRIVATE
-ChanServ- Prefix     : ! (default)
-ChanServ- *** End of Info ***

Channel registered by user that used unicode char:
-> *ChanServ* INFO #kill‌
-ChanServ- Information on #kill‌:
-ChanServ- Founder    : devnull
-ChanServ- Successor  : CaneNero
-ChanServ- Registered : Aug 04 09:18:37 2016 +0200 (1d 14h 18m 7s ago)
-ChanServ- Mode lock  : +nt-lk
-ChanServ- Flags      : SECURE KEEPTOPIC FANTASY
-ChanServ- Prefix     : ! (default)
-ChanServ- *** End of Info ***

On atheme-services-7.2.6

**Comment by GLolol** [comment]
I feel like this is more of an issue that should be dealt with IRCd-side. If these channel names are blocked IRCd-side, nobody can join them and register them.

**Comment by Doemela** [comment]
Have made ticket also with IRCD but its not the name that has to be blocked but the unicode behind that is a space so nobody sees it

**Comment by siniStar7boy** [comment]
I also tend to agree that this is more of an IRCd issue than an Atheme issue.  

As far as the ticket with the IRCD, give them time to see the ticket and respond.  _(Developers may have to further look into the issue, so I would not expect an immediate response; but one soon..)_

**Comment by Doemela** [comment]
Can be done with U+200A U+200B U+200C U+00A0 U+202E U+2000 U+2001 U+2002 U+2003 U+2004 U+2005 U+2006 U+2007 U+2008 U+2009 U+202F U+205F So with normal chan u can create 18 channels without anybody can see the diffrence

**Comment by kaniini** [comment]
There is no bug here.
Channel names are sequences of bytes.  The channel name while visually similar is different.
Request a clarification from the IRCv3 group if you disagree with this.

(Most IRCd software do however, have a feature to drop whitespace characters.  What IRCd is it?)

**Comment by kaniini** [comment]
Closing the issue as there is no bug here.  Atheme is required to support registration of any channel presented to it by the IRCd.
