### ISSUE TITLE
Chanserv does not consistently unban users after an akick expires

### ISSUE THREAD

**Issue by tonyravioli** [atheme/atheme#520]
#donger on Freenode is [a game](https://github.com/tonyravioli/dongerdong) where, under certain conditions (the losing of a "deathmatch"), an akick is set through CHANSERV (/msg CHANSERV akick add #donger (hostmask) !T 20).

90% of the time, it works great - but occasionally it will simply fail to unban the user from the channel after the AKICK timer runs out. I've gotten into the habit of occasionally clearing bans manually (chanserv does not re-kickban these users when they enter the channel, since they're no longer on the AKICK list), but it can be frustrating for users who are banned for days before I realize they're still banned.

I mentioned this in #Freenode and they suggested I fill out a ticket here.

**Comment by Zarthus** [comment]
Do you have some example cases where it does not unban the user?

I can imagine some scenarios where this might be the case (setting an akick on an account, but then the user logs off.)

I don't think you should use AKICK automated through a bot at all and implement your own timeban system, but I also don't see much value to a game that removes you from the channel when you lose. 

I suppose the issue remains valid, but I don't think services can do much about it without actively trying to find all the hosts the user might have used. It'll be better if your bot set a manual time ban with mode +b.

**Comment by Zarthus** [comment]
Refers to when an authenticated user gets AKICKed (by account name), but logs off in the interim and is not online when the AKICK expires. There is no host to look up as the user is not online, and therefore it does not get unbanned.

To fix this, AKICK the hostname instead.

I don't think this is something Atheme [cws]hould fix. Atheme does not manage your banlist, the ircd/channel ops do. Banlist functionality might be a nice thing to incorporate (ala eir), but that would be a separate suggestion.

**Comment by tonyravioli** [comment]
Thanks for checking into this! I understand how Chanserv works a little better now.
