### ISSUE TITLE
ChanServ support clear +q /cs clear #chan quiet

### ISSUE THREAD

**Issue by Arkadietz** [atheme/atheme#521]
Hello,

It will be possible to introduce a new option for cleaning all +q  modes in the channel ?
Will be very helpful! 

Example of +q in #Bulgaria
#Bulgaria q *!*5f0985fc@*.html.chat Kiril!kiril@kiril.eggheads.org 1475424954
#Bulgaria q *!*5ebec102@*.html.chat Dracarys!Dracarys@bUrn.thEm.aLL 1474894095
#Bulgaria q *!*4dde3d0e@*.html.chat zeus.abvnet.org 1474492920
#Bulgaria q *!*d4059e9f@*.html.chat zeus.abvnet.org 1474492920
#Bulgaria q *!*5cf77cfd@*.html.chat zeus.abvnet.org 1474492920
#Bulgaria q End of Channel Quiet List

Example of the future command:
/cs clear #Bulgaria quiet

**Comment by maxteufel** [comment]
This is already implemented, read `/msg ChanServ help clear bans`. You're looking for `/msg ChanServ CLEAR #channel BANS q`.
