### ISSUE TITLE
AKICK add no nickname but *!*nickname

### ISSUE THREAD

**Issue by Doemela** [atheme/atheme#527]
I use latest version of atheme
`/msg chanserv akick #test add nickname !T 365d Bottest`
I get `-ChanServ- AKICK on *!*@nickname was successfully added for #test and will expire in 365 days, 0:00:00.`

Can anybody look on the why it does not work

**Comment by siniStar7boy** [comment]
Because a user named 'nickname' is not present on the channel, therefor ChanServ thinks you are wanting to add a hostmask akick.
