### ISSUE TITLE
MemoServ should remind the user that inbox is full

### ISSUE THREAD

**Issue by Gryllida** [atheme/atheme#531]
When a user logs in, MemoServ should be able to remind them that their inbox is full. This should be configurable in atheme config file (and also perhaps a user needs to be able to opt out of the reminder).

Steps to reproduce:
1. get many memos and reach the limit

Expected result:
1. user is made aware of the limit being reached at least once, or is reminded regularly (on-login, when the user removes /away status, by email, or something else)

Actual result:
1. afaik nothing happens at all (people who try to send me memos get an error message, but I don't)

**Comment by aaronmdjones** [comment]
Do those commits resolve the issue?

**Comment by Xenthys** [comment]
@aaronmdjones The services crashed with that. Here is the backtrace:
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fe07ff60d28 in on_user_identify (u=0x7ffc87dfe660) at main.c:55
55						ircd->uses_rcommand ? "" : "msg ", memosvs->disp);
```

**Comment by Xenthys** [comment]
It's all fixed, it was indeed a MODUNLOAD / MODRELOAD issue.
The reminder works, this issue can be closed.

**Comment by aaronmdjones** [comment]
Thanks.
