### ISSUE TITLE
Module for forcing all users to logout / crypt transitioning 

### ISSUE THREAD

**Issue by Arkadietz** [atheme/atheme#542]
Hello,

I am writing this in matter if i knew C, C++ i will done for myself. So if is possible to make a new module to force all users to logout. 
This is a big pain in the ass when it's come this moment and have to wait endless time instead this happing for a couple a days most or max for the expiration period.

Example:
verify_password(): transitioning from crypt scheme 'rawsha1' to 'pbkdf2v2' for account 'Ivelina'

Best regards,

Kiril

**Comment by Zarthus** [comment]
As we said on IRC, keeping the module loaded isn't that big of a problem.

If you force logout everyone, you'll also face the issue of some nicks expiring because people thought they were logged in, but forcefully got logged out without their knowledge.

Why can't you just send a few global notices?

**Comment by kaniini** [comment]
I did it the way it is on purpose, but since I don't care anymore, I'll let someone else comment.

**Comment by siniStar7boy** [comment]
There is no need for this, in my opinion.  Forcing a logout for everyone is not a good idea.  In fact, it is un-necessary and likely just going to create issues for your users. _(As mentioned by @Zarthus above)_  

Your users will be migrated to the new encryption as they naturally come and go.  **Unless there is a further compelling reason for force-logging everyone out or an interest in writing such a module by any other atheme developers**, _I will close this issue_.  

If you are that worried about forcing everyone to the new encryption type, this can be done in other ways such as _restarting servers and forcing everyone to reconnect_ -- or _you could send a global message_, or even _add to the announcements sent to user on connect_.

**Comment by ilbelkyr** [comment]
- If your concern is that people should use the better hashing method as soon as possible, send out notifications.
- If your concern is about the line cluttering up your services logs, adjust your log level.
- If your concern is about keeping the module loaded, I have not seen an argument as to why this concern is warranted. You say it's a "pain in the ass", but to be quite honest, keeping the module loaded does not sound like it would take a lot of effort.

Logging out everyone is easy enough to do from a module, but in this case, it would be a solution to a non-problem as far as I can tell. Closing for now.
