### ISSUE TITLE
GameServ: Use arc4random_uniform rather than arc4random modulo

### ISSUE THREAD

**Issue by pinkgothic** [atheme/atheme#551]
Hi, guys! Thanks for your work on these services. :)

GameServ currently seems to be using arc4random() % range as its PRNG:

https://github.com/atheme/atheme/blob/master/modules/gameserv/dice.c#L540

Since from my understanding, this approach might have a modulo bias (see http://stackoverflow.com/a/29956021/245790), it would be nice if we could swap this around to arc4random_uniform().

If there are worries about the function not being present in systems that services should be compiled on, there's one variant here: http://cvsweb.openbsd.org/cgi-bin/cvsweb/src/lib/libc/crypt/arc4random.c?rev=1.40&content-type=text/x-cvsweb-markup (even though I admit the loop does make me twitch, but apparently that's standard practise for this kind of range mapping)

Thanks for reading!

**Comment by grawity** [comment]
arc4random isn't present in most systems either, so we already copied all of it from openssh-portable. I think that includes _uniform and everything.

I'm not sure about the loop, but if it generally finishes within a few iterations, then a patch for GameServ should be fine.
