### ISSUE TITLE
ChanServ not setting +r on registered channels on UnrealIRCd 4.0.12

### ISSUE THREAD

**Issue by Kelerei** [atheme/atheme#555]
Hi,

Using Atheme 7.2.9 and UnrealIRCd 4.0.12.

I've noticed that ChanServ does not set channel mode +r (used to denote that the channel is registered) on registered channels.  Other services packages do set this mode on channel registration and recreation of a registered channel, and unset it if the channel is dropped for any reason.  Could this please be added in future?

**Comment by grawity** [comment]
Is that mode actually useful for something? Afaik it's basically a leftover...

**Comment by vectr0n** [comment]
https://github.com/atheme/atheme-contrib-modules/blob/master/cs_regmode.c there is a contrib module to set this on channel register

**Comment by Kelerei** [comment]
Ah right.  I totally missed that contrib module -- thanks!

The one thing it doesn't do that it possibly could is set +r on registered channel recreation.  Shouldn't be too difficult for me to add in; I'll give it a go and submit a PR once done.
