### ISSUE TITLE
protocol/unreal4 - possibly support usermode +Z

### ISSUE THREAD

**Issue by Kelerei** [atheme/atheme#556]
Hi,

UnrealIRCd has added a new user mode in 4.0.12, released around a week ago.  This may need support in Atheme (or may not, I'm not sure -- thought I'd let you know anyway in case it does indeed need support).

From the [changelog](https://forums.unrealircd.org/viewtopic.php?f=1&t=8713), this is what they added:

> New user mode +Z: Only allow SSL/TLS users to private message you.

**Comment by alyx** [comment]
Since Atheme doesn't really touch umodes, this isn't one we should have to mess with. Thanks for keeping us updated though! :smile:
