### ISSUE TITLE
Does the Anope [2.0.*] to Atheme database conversion work?

### ISSUE THREAD

**Issue by TheMythPT** [atheme/atheme#558]
i've recently cloned the repo and i'd like to give Atheme a try. But i do have already a Anope v2.0.5 database.  Does anope-1.9.2-convert.php will work? Any other database converter?
Best regards-

**Comment by siniStar7boy** [comment]
The database conversions have not been updated in quite a while.    

As to whether it would work: _you could try it and let us know of success or hiccups/failure._  

**(But first; make backups of the database in case it hiccups or has any "surprises")**

**Comment by siniStar7boy** [comment]
Closing due to lack of response/information - if the database conversion tool does not work; re-open under a new issue that verifies that and provide more _details_.
