### ISSUE TITLE
Any problem with new OpenSSL versions?

### ISSUE THREAD

**Issue by communered** [atheme/atheme#583]
Does Atheme compatible with only OpenSSL 1.0.x? I got strange error yesterday when i tried to start atheme.

It was asking for missing files: libssl.so.1.0.0 and libcrypto.so.1.0 on libmowgli-2
 settings, also libcrack.so.2. Shall i use only gnutls?

Atheme version: 7.2.9
System: Debian 9.1

**Comment by maxteufel** [comment]
Debian 9 ships OpenSSL 1.1.x now. Because you probably compiled your Atheme before that update of OpenSSL, it now can't find the files anymore. You need to rebuild it. (Same applies to libcrack, most likely.)
