### ISSUE TITLE
InfoServ: allow swapping & removing date/time from logon news

### ISSUE THREAD

**Issue by Mikaela** [atheme/atheme#597]
I think that on all networks that I have seen InfoServ being used on, all posts are static and sent ages ago.

Thus I would like to see InfoServ supporting not showing logon info date/time at all, but instead statically in format e.g.: 

```
-InfoServ- *** Message(s) of the Day ***
-InfoServ- [HELP] Remember that for help you can always /join #help 
-InfoServ- [DOCUMENTATION] You can find the documentation at https://wiki.example.net/
-InfoServ- [FIREWALL] Please run software firewall on your host while using IRC
-InfoServ- *** End of Message(s) of the Day ***
```

Where there is just the MOTD begin, subjects and the messages rather than

```
-InfoServ- *** Message(s) of the Day ***
-InfoServ- [SUBJECT] Notice from Mikaela, posted 08:08 on 11/21/2017:
-InfoServ- BLAH BLAH BLAH
-InfoServ- [SUBJECT2] Notice from Mikaela, posted 08:08 on 11/21/2017:
-InfoServ- BLAH BLAH BLAH BLAH
-InfoServ- [SUBJECT3] Notice from Mikaela, posted 08:08 on 11/21/2017:
-InfoServ- BLAH BLAH BLAH BLAH BLAH
-InfoServ- *** End of Message(s) of the Day ***
```

I think that simultaneously it would be useful to be able to manage the order in which InfoServ logon news are sent without having to remove all posts and writing them again.

**Comment by janicez** [comment]
Really a great idea. Can't believe I didn't think of it.
