### ISSUE TITLE
"CLEAR FLAGS" does not need to check if a registered channel exists

### ISSUE THREAD

**Issue by xnrand** [atheme/atheme#605]
[There is a check](https://github.com/atheme/atheme/blob/release/7.2/modules/chanserv/clear_flags.c#L63) which prevents founders from clearing the flags of channels that are currently empty.
My suggestion is to remove this restriction.

**Comment by siniStar7boy** [comment]
I am not sure why this is even an issue..  If the channel is not in use, why not just DROP it?  I do not see a beneficial reason to remove the said check.

**Comment by xnrand** [comment]
When I stumbled over this restriction, my situation was that I wanted to reopen an old channel (restricted flag on, a few ACL entries, currently empty). Having removed the restricted flag, I wanted to clear out the ACL and set up a few things first.

Of course, this is easy to work around this by joining the channel. However, I don't see any beneficial reason why the restriction _exists_ in the first place.

More than that, it's unintuitive: Other operations on channel ACLs don't require the channel to exist. An empty channel's ACL can be cleared out manually by issuing a bunch of "FLAGS" commands just fine. However, going the "CLEAR" route requires it to exist. Why?

**Comment by siniStar7boy** [comment]
Closing, a PR was already merged for this..
