### ISSUE TITLE
Plugin compilation error

### ISSUE THREAD

**Issue by Aideux** [atheme/atheme#622]
Okay I'm having a particular issue during compilation using the command `gcc -shared -o attack_test.so -fPIC attack_test.c.` Specifically, when I run the command, I get the error `fatal error: ec.h: No such file or directory.` Any idea how to fix this issue? Thanks.

[EDIT] To give a little more issue background, I'm running this command from the desktop, where my C source code is located. Perhaps there's a specific place I need to put the source and run the command?

**Comment by aaronmdjones** [comment]
Are you sure it shouldn't be including `<openssl/ec.h>` instead of `<ec.h>` ?
Additionally, you can put this inside an `#ifdef HAVE_OPENSSL_EC_H`

**Comment by aaronmdjones** [comment]
Ideally you would put the source file into `modules/misc/` and edit `modules/misc/Makefile` to reference it in `SRCS`. Then you can `make` in that directory or the root directory and it will compile it with all of the usual `CFLAGS` / `CPPFLAGS` / `LDFLAGS` / `LIBS` that the rest of the project uses.

**Comment by Aideux** [comment]
Could you put the entire filepath for the `modules/misc/Makefile`? I'm having trouble finding it, leading me to believe that my Ettercap isn't installed properly...

**Comment by aaronmdjones** [comment]
Uh, I think you have the wrong GitHub repository, this is for Atheme IRC Services (NickServ, ChanServ, et al)

**Comment by Aideux** [comment]
Oops!! Sorry! Thank you haha
