### ISSUE TITLE
Feature Request: Privilege for automatic identification as any user

### ISSUE THREAD

**Issue by sebastiannielsen** [atheme/atheme#624]
I suggest the following userpriv is added:

user:pretenduser

example:
```
privs {
         user:pretenduser
};
```

When someone with this privilege Active uses a nick of a registred user, NickServ will NOT ask for identification, instead it will automatically identify as that user account for which the nick belongs to, like the password was typed.
The user with this privilege will then aquire all the rights the registred user has, including any channel statuses, any rights the user has access to, memos, and any accesses the user is present for, and also it will Count as a login (so inactivity timer is reset for example)
 
Example:
If TestUser are a channel founder in #channela and #channelb and AOP in #channelc 

TestUser is not currently online (Or I through an Oper-command force-change TestUser nick to something else)
Then I type /nick TestUser
If I then have user:pretenduser privilege, NickServ will then not ask for password, but will instead directly tell: `<NickServ> You are now identified for TestUser` and I will become channel founder in #channela #channelb and AOP in #channelc

The idea of this priv, is to allow "Super IRCOps" to pretend to be any user on the network, for the purpose of network administration. (Of course you can't pretend a user that is online, but then the IRCOp has to force-change that user's nick using normal oper commands Before pretending)

**Comment by aaronmdjones** [comment]
You can already impersonate other users with SASL logins (if your client supports this) and one of the impersonation privileges (documented in `doc/PRIVILEGES`).

**Comment by sebastiannielsen** [comment]
My idea was to extend this functionality to non-SASL capable clients by implementing a privilege that works with normal OperServ/NickServ.

**Comment by aaronmdjones** [comment]
This is extremely unlikely to be implemented as already discussed on IRC.

**Comment by siniStar7boy** [comment]
Closing, as this will **never** be implemented - and I do not want to lead users into thinking it ever _**may**_.

This _(as discussed on IRC)_ is not ethical.  Atheme has _never_ been about providing _"godly"_ or _"secretly invasive"_ features or modules -- it has been quite vocally opposing of such.  _(Why we TAINT on detection of invisibility _(spy)_ modules, and are quite verbose in _"forced"_ actions by on or by other users.)_

There are better ways via your ircd and atheme to handle network abuse at an oper level.

**Comment by kaniini** [comment]
@siniStar7boy just made my day by verifying that atheme is sticking to it's roots
