### ISSUE TITLE
Parse error in inspircd.conf with Atheme

### ISSUE THREAD

**Issue by yuljk** [atheme/atheme#626]
Hi guys - I've configured Atheme with InspIRCD - however when I attempt to restart the inspircd service I get a parse error as per below

`Invalid XML entity name in value of <chanprotect:aprefix>
To include an ampersand or quote, use &amp; or &quot;
Parse error at /home/inspircd/inspircd-2.0.26/run/conf/inspircd.conf:155:20 (inside tag chanprotect at line 153)
`
This is the section it is referring to..

<chanprotect
         noservices="no"  < This line
         qprefix="~"
         aprefix="&">

According to the documentation I've looked at this looks to be correct - why is this parsing incorrectly?

Any help much appreciated!

Cheers

**Comment by Zarthus** [comment]
This is the issue repository for atheme, not for inspircd.

Your error seems to be inspircd related?

**Comment by vectr0n** [comment]
You have to use it exactly like the example conf suggest..

https://github.com/inspircd/inspircd/blob/insp20/docs/conf/modules.conf.example#L439-L440

**Comment by yuljk** [comment]
Hi - This is only after adding the chanprotect section for Atheme to inspircd.conf.  I'll raise the issue with them and see how I get on.

Many thanks

**Comment by yuljk** [comment]
Thanks vectr0n - That seems to have cleared up the issue.

Many thanks
