### ISSUE TITLE
NickServ appears offline in ngircd

### ISSUE THREAD

**Issue by slackhead** [atheme/atheme#633]
I'm using latest atheme with ngircd 24 and I'm connecting with pidgin.

NickServ always appears offline. I've tried playing with all the settings I can see in both ngircd and atheme but can't figure out why.

Because of this I can't identify when I connect with pidgin because pounces need to see if it comes online etc.

ngircd settings:

[SERVER]
  Name = services.
  Host =
  Port =
  SSLConnect = no
  MyPassword = xxxxxxx
  PeerPassword = xxxxxxx
  ServiceMask = *Serv
  Group = -1
  Passive = no

Any ideas?

*Edit

Is should add that nickserv works fine in every other way, and even sends me a message that my nick is a registered nick and I should auth etc.

**Comment by grawity** [comment]
Connect using a dedicated IRC client and check what's shown by `/whois nickserv`.

Try running Atheme in console/debug mode, with the parameters `-d -n`, and post the logs here.

(Honestly, ngIRCd should just add SASL support already...)

**Comment by slackhead** [comment]
I had no reply back from /whois in weechat. By the way, NickServ does appear online in pidgin on freenode.

Log attached.

[atheme.log](https://github.com/atheme/atheme/files/2237964/atheme.log)

**Comment by grawity** [comment]
Hmm, it's sending the /whois reply to sid 00A, but I don't think ngIRCd even _supports_ sids... If you have this configured in atheme.conf, remove it.

(Tbh I think it's a bug that it uses sids despite the protocol module telling it otherwise.)

**Comment by grawity** [comment]
Also, regarding identify on connect: most ircds also support forwarding the "server password" to services (e.g. freenode) – check whether this works with ngIRCd. It'd still be a simpler method than relying on Pidgin's "pounces".

**Comment by slackhead** [comment]
Now I've removed the numeric I am getting /whois back in weechat. Still no luck in pidgin though.

I'll give your suggestion a try.

To be honest the only reason I'm using pidgin for this server is because I'm already using pidgin for a few facebook friends and this IRC server is just for me and a few friends which I'd like to keep separate from weehcat at the moment.

**Comment by slackhead** [comment]
It looks liek ngircd doesn't forward the server password. I just get connection refused for wrong password.

Something else I've noticed /whois info for nickserv doesn't show any online/idle/away info/time like it does for a normal user. Could that be the problem?

**Comment by slackhead** [comment]
Well it appears that freenode services are setup the same way, and it works fine with those.

It seems that it would be better if ngircd supported custom commands/aliases or even just the /nickserv command, or if pidgin IRC helper plugin was better setup to support /msg nickserv as an option instead of just /nickserv which ngircd borks at. From what I found looking around for solutions, pidgin isn't the only client that has this problem with the /nickserv command on some servers, but the problem is really with the IRCd.

Thanks for your help though. I'll still keep using atheme because it works fine for me.

**Comment by jlu5** [comment]
Re https://github.com/atheme/atheme/issues/633#issuecomment-408605386: I think I fixed this in https://github.com/atheme/atheme/pull/570, but that's only in master and not release/7.2

**Comment by slackhead** [comment]
OK, thanks. I can probably make a patch for that (and maybe other commits since 7.2).
