### ISSUE TITLE
Wasn't able to use email address with apostrophe...

### ISSUE THREAD

**Issue by oofoe** [atheme/atheme#638]
Hi!

I had to use an email address that didn't include an apostrophe. However, apostrophe's are allowed characters as per RFC2822.
  
There may be other people who have this problem, but don't have alternate addresses available. If you have a chance to look into this, the following articles might be helpful:
  
   * https://tools.ietf.org/html/rfc2822#section-3.4.1
   * https://haacked.com/archive/2007/08/21/i-knew-how-to-validate-an-email-address-until-i.aspx/

emerson via RT <support@freenode.net> suggested I file a bug report here. See freenode.net #212050.

Thanks very much!

**Comment by aaronmdjones** [comment]
This was already resolved last year in commit a82ad4285259423bbffa on the master branch. When version 7.3.0 is released, @freenode will migrate to that, and then you will be able to use such an e-mail address.
