### ISSUE TITLE
NickServ waitreg missing

### ISSUE THREAD

**Issue by Casey952** [atheme/atheme#645]
7.3.0
NickServ waitreg is missing from the load modules and the NickServ config block in atheme.conf

**Comment by Casey952** [comment]
sorry,
waitreg and the other ones listlogins and genhash that were also added in the commits are not added into `#loadmodule` - just the list * modules

`* Delay services account registrations modules/nickserv/waitreg`

**Comment by aaronmdjones** [comment]
Apologies. The modules have commented-out `loadmodule` lines now.
