### ISSUE TITLE
Advertise SASL mechanisms to unrealircd4 servers

### ISSUE THREAD

**Issue by matildel** [atheme/atheme#647]
This patch by syzop from xtheme would implement that feature in the protocol module for unrealircd.
https://github.com/XthemeOrg/Xtheme/commit/30fcd1f93e7155eacd9d933b72fb6b1f4013fe92

**Comment by aaronmdjones** [comment]
This patch was already applied more than a year ago, in commit 65008c05cfecc8fdc07830dcaba8b0e547991cae.
