### ISSUE TITLE
Feature Request: maxlogins per account

### ISSUE THREAD

**Issue by cooldude13233** [atheme/atheme#652]
I hope that some dev implements some module of specifying maxlogins per account instead of having to justify maxlogins on accounts network wide

**Comment by alyx** [comment]
Can you clarify the benefit of this feature?

**Comment by cooldude13233** [comment]
@alyx it’s so that accounts are to have flexibility to link other nicknames together instead of being constrained by the global limit specified by default

**Comment by jesopo** [comment]
the usecase I care about here is things like services bots that all do a similar thing but are split in to separate instances, for whatever reason.

I think there's two options here:

1. have two categories for `OS SET MAXLOGINS` - a low and a high limit, where a flag to use the high limit is set on accounts
2. a privileged `NS SET MAXLOGINS` that, without being set, defaults to `me.maxlogins`

any better ideas?

**Comment by alyx** [comment]
Looking at it from an oper perspective makes sense. The one thing I'd wonder is, if we're going in from an OS perspective anyway, would it be better to have a high limit (and thus, still have a limit that will somehow end up being hit again) or just bump it to "unlimited logins"?

**Comment by jesopo** [comment]
how about something like `NS LOGINLIMIT <nick> ON|OFF` or so?

has been discussed that an FSET with privilege control over each possible setting would be nice but that's a bigger discussion

**Comment by ilbelkyr** [comment]
fixed with #723, I'd say
