### ISSUE TITLE
which one atheme service support for bahamut version 2.1.4

### ISSUE THREAD

**Issue by shahkacak369** [atheme/atheme#664]
helo.. any one know which one version of atheme service support for bahamut 2.1.4 ..

**Comment by alyx** [comment]
Atheme 7.2 supports Bahamut protocol as of 1.8.x -- this results in full compatibility with the exception of channel modes +P (disable spamfilter) and +A (auditorium).

As of cd2e3b5, full support for Bahamut 2.x protocol, including cmodes +P/+A is now available.

**Comment by shahkacak369** [comment]
As of cd2e3b5
<https://github.com/atheme/atheme/commit/cd2e3b5cadf1dc0f7f636376fcabf93fb69b7b7d>
<<----
where to download if want use this

**Comment by alyx** [comment]
`git clone -b master https://github.com/atheme/atheme.git`
