### ISSUE TITLE
chanfix not fix channel from ban or op for users register

### ISSUE THREAD

**Issue by darksis** [atheme/atheme#668]
hello when users register to nickserv and after create a new channel chanfix not really help if the owner in channel get ban or deop him then the question if this a possible set options for users register or users normal them create a channel chanfix can fix ban or deop or other modes

**Comment by ilbelkyr** [comment]
From what you're describing, it sounds like what you want is to register the channel with ChanServ, which does provide a means of channel ownership; ChanFix is more of a tool to recover EFnet-style channels without a clearly defined channel ownership if they end up without ops.
