### ISSUE TITLE
Fatal Error during Make

### ISSUE THREAD

**Issue by anlarye** [atheme/atheme#679]
I received the following errors during "make" this is on Ubuntu 18.04

version.c:9:10: fatal error: serno.h: No such file or directory
 #include "serno.h"
          ^~~~~~~~~
compilation terminated.
../buildsys.mk:319: recipe for target 'version.lib.o' failed
make[1]: *** [version.lib.o] Error 1
buildsys.mk:120: recipe for target 'libathemecore' failed
make: *** [libathemecore] Error 2****

**Comment by ilbelkyr** [comment]
Please see [the official instructions for obtaining the Atheme source][obtaining] for information; the message you're encountering normally indicates trying to build from a snapshot of the repository with neither the actual `.git` repository nor an appropriately generated `serno.h` file included.

[obtaining]: https://github.com/atheme/atheme#obtaining-atheme
