### ISSUE TITLE
module: change nick problem

### ISSUE THREAD

**Issue by r3k2** [atheme/atheme#681]
Hello we are trying to write a module that will auto change the nick to something like the enforcer.c does with guest{ramdon number}.
it works but only on server side. the IRC client does not update so it creates issues joining channels etc..

```
clean_nickname(user_t *u)
{
	char nickbuf[COMPAT_NICKLEN];  
        return_if_fail(u != NULL);	
	snprintf(nickbuf, sizeof nickbuf, "%s%d", "cat", arc4random()%100000);

	notice(nicksvs.nick, u->nick, "Your nick has been changed to \2%s\2 per %s nickname quality guidelines.", nickbuf, me.netname);

	fnc_sts(nicksvs.me->me, u, nickbuf, FNC_FORCE);
}
```

seems that on weechat I have this issue, and kvirc but I been told some other clients do not have the issue...
can someone point me to the right documentation or a pointer for this to work?
I been like crazy googling for a list of calls hooks etc with no succeed so we been basically reading other peoples modules trying to make sense of it.

thanks

**Comment by juggs** [comment]
Is this not a client issue rather than server side?

HexChat client certainly has no problem understanding when atheme (vanilla) forces a nick change.

https://hexchat.github.io/downloads.html

Do weechat and kvirc respect vanilla atheme enforced nick changes OK?

**Comment by ReK2Fernandez** [comment]
@juggs I do not think is a client issue because it works fine with the regular services as far as I can tell.

**Comment by ReK2Fernandez** [comment]
@juggs  I updated the other linked issue with the module we trying to get working if you want to check in case there is something bad done, since is my first module, make sure is not in my code the issue..

**Comment by ilbelkyr** [comment]
Looks like this is a bit of an old issue. I can't reproduce such an issue relating to forced nick changes, so perhaps it's going wrong at some other point – maybe on the client side, maybe on the ircd side.

If you can reproduce this, please do comment giving more details (including the full code of the module as well as the version of Atheme, your IRCd, and your IRC client) and I'll see if we can figure out what's going wrong. Thanks!
