### ISSUE TITLE
[Need Fix] /etc/init.d/atheme-services

### ISSUE THREAD

**Issue by MikkelDK** [atheme/atheme#682]
Hi,

**/etc/init.d/atheme-services** need to be fixed, because; it giving errors - as example this:
```bash
Dec 11 10:58:43 atheme-services[30982]: [2019-12-11 10:58:43] (confparse.c:81 mowgli_config_file_error): mowgli_config_file_parse(): Couldn't open "/etc/atheme/atheme.conf": Permission denied
Dec 11 10:58:43 atheme-services[30982]: [2019-12-11 10:58:43] Error loading config file /etc/atheme/atheme.conf, aborting
```
So actually, I did check on the code. and seems "irc" user needs to be created before it can get access to atheme.conf because it's locked to "root:root" - like an example.

**Update**: It will starting manually as root, if I only typo: **./atheme-services**

**Comment by grawity** [comment]
Initscripts and service user accounts are provided by your Linux distro, not by Atheme developers.
