### ISSUE TITLE
Services Language 

### ISSUE THREAD

**Issue by AnaxArxes** [atheme/atheme#687]
How can I make the language of services in Turkish?

**Comment by Mikaela** [comment]
I think if you have compiled Atheme with support for translations, you can `/msg NickServ SET LANGUAGE tr`.

**Comment by AnaxArxes** [comment]
-> *NickServ* SET LANGUAGE tr
-NickServ- Invalid language tr.
-NickServ- Valid languages are: en de da fr es cy ru

**Comment by Mikaela** [comment]
Which version are you using?

**Comment by AnaxArxes** [comment]
atheme-v7.2.10-r2

**Comment by Mikaela** [comment]
[7.2.10-r2](https://github.com/atheme/atheme/releases/tag/v7.2.10-r2) seems to have been released on Jul 5, 2018 while tr.po has been added on Dec 26, 2018.

I guess you can try coping `po/tr.po` from the newer version in case it still works or try using git version or wait for the new version to be released.

**Comment by alyx** [comment]
Since the original author hasn't updated this in a few months, I'm going to close this. Feel free to reopen if this issue reoccurs :)
