### ISSUE TITLE
channel register does not get all founder flags

### ISSUE THREAD

**Issue by Casey952** [atheme/atheme#695]
Atheme 7.2.10-r2

When you register a channel, it does not get all flags.

It does not get "e"

FOUNDER              +AFORaefhioqrstv

#channel +AFORafhioqrstv

**Comment by ilbelkyr** [comment]
(This should be fixed now)

**Comment by Casey952** [comment]
@ilbelkyr 

For a transfer of founder to a new person and or successor, this was missing exempt aswell.

If this is now fixed or needs to have CA_EXEMPT added to:

```
/* granted to new founder on transfer etc: */
#define CA_FOUNDER_0     (CA_SUCCESSOR_0 | CA_FLAGS | CA_USEOWNER | CA_FOUNDER)
```

- This fix was added to Xtheme with exempt added to new founder on transfer etc.

```
Xtheme

/* xOP defaults, compatible with Atheme 0.3 */
#define CA_VOP_DEF       (CA_VOICE | CA_AUTOVOICE | CA_ACLVIEW)
#define CA_HOP_DEF	 (CA_VOICE | CA_HALFOP | CA_AUTOHALFOP | CA_TOPIC | CA_ACLVIEW)
#define CA_AOP_DEF       (CA_VOICE | CA_HALFOP | CA_OP | CA_AUTOOP | CA_TOPIC | CA_ACLVIEW)
#define CA_SOP_DEF       (CA_AOP_DEF | CA_SET | CA_REMOVE | CA_INVITE)

/* special values for founder/successor -- jilles */
/* used in shrike flatfile conversion: */
#define CA_SUCCESSOR_0   (CA_VOICE | CA_OP | CA_AUTOOP | CA_TOPIC | CA_SET | CA_REMOVE | CA_INVITE | CA_RECOVER | CA_FLAGS | CA_HALFOP | CA_ACLVIEW | CA_USEPROTECT)
/* granted to new founder on transfer etc: */
#define CA_FOUNDER_0     (CA_SUCCESSOR_0 | CA_FLAGS | CA_USEOWNER | CA_FOUNDER | CA_EXEMPT)
/* granted to founder on new channel: */
#define CA_INITIAL       (CA_FOUNDER_0 | CA_AUTOOP | CA_EXEMPT)
```

**Comment by ilbelkyr** [comment]
`CA_FOUNDER_0` is defined in terms of `CA_SUCCESSOR_0` (and `CA_INITIAL` in turn is defined in terms of that), so it'll have `CA_EXEMPT` as well now that it's been added to that.

(The fix you've included does address your issue, but doesn't add `CA_EXEMPT` to `CA_SOP_DEF` and `CA_SUCCESSOR_0`, both of which used to include the same degree of access before `+e` was made separate from `+r`, so in my opinion it's more proper to add it to these too)
