### ISSUE TITLE
[7.3.0-rc2]: AKICK Adding|Deleting issues

### ISSUE THREAD

**Issue by westor7** [atheme/atheme#704]
Hello,

I was testing the 7.3.0-rc2 and i noticed that when i have SYNC option enabled on the channel and trying to add a new AKICK on a registered nickname (WITHOUT ANY ACCESS FLAGS) it doesn't automatically sync to kickban that user out, and the same has to be done when i remove the AKICK and a ban was listed, it doesn't remove it, so after each addition or deletion i have to use /cs sync #channel (!sync) in order to take action.

For Example:

`!akick add nickname test`
`westor added nickname to the AKICK list, expires in 90 days, 0:00:00.`
`ChanServ sets mode: +b *!*@90A4A42.A81B872.668AD4CD.IP <---- MISSING`
`nickname was kicked from #Channel by ChanServ (Banned: test) <---- MISSING`

So when i adding a new nickname on the AKICK list it should have take action on ban+kick but didn't.

The strange part of this issue is that is working as expected on hostmask.

Fo Example:

`!akick add *!*@90A4A42.A81B872.668AD4CD.IP test`
`westor added *!*@90A4A42.A81B872.668AD4CD.IP to the AKICK list, expires in 90 days, 0:00:00.`
`ChanServ sets mode: +b *!*@90A4A42.A81B872.668AD4CD.IP`
`nickname was kicked from #Channel by ChanServ (Banned: test)`

-----------------

An other AKICK related issue is that, when i am trying to ADD a new akick on an UNREGISTERED nickname it doesn't adding the nickname correctly or the hostmask (i don't know which it should add in that case, i think the hostmask based on nickname!ident@host) but it keeps adding an incorrect hostmask entry.

For Example:

`!akick add irccloud testing`
`westor added *!*@irccloud to the AKICK list, expires in 90 days, 0:00:00.`

In the above example it seems adding the nickname incorrectly in order to not match for ban+kick him out.

- Thanks!

**Comment by alyx** [comment]
That is unusual; can you clarify what IRCd you're using?

**Comment by westor7** [comment]
UnrealIRCD 5.0.5.1
