### ISSUE TITLE
[7.3.0-rc2]: /ns release keeps releasing a nickname that is not enforced

### ISSUE THREAD

**Issue by westor7** [atheme/atheme#706]
Hello,

I was testing the 7.3.0-rc2 and i noticed that when someone uses /ns release nickname password and that nickname is not in services enforce state it keeps accepting the release command.

For example:
I am connecting with an unregistered nickname "tester" and my head nickname name is "main" but my nickname is logged off , if i execute /ns release main password it says that my nickname was released that it shouldn't because it wasn't in any enforce state.

`/nick tester`
`/server .. ... .`
`/ns release main mypassword_here`
`/ns release main mypassword_here`
`/ns release main mypassword_here`
`main has been released.`
`main has been released.`
`main has been released.`

- Thanks!

**Comment by alyx** [comment]
This is intentional; some IRCds apply the enforcer via a server block on the nickname instead of a pseudoclient, so we allow release to be used when not necessary in case of a desync between Atheme and the IRCd.
