### ISSUE TITLE
[7.3.0-rc2]: /ns regain it seems working like /ns identify in some cases

### ISSUE THREAD

**Issue by westor7** [atheme/atheme#707]
Hello,

I was testing the 7.3.0-rc2 and i noticed that when someone uses /ns regain to get back his already in use nickname but his nickname is NOT in use by someone else then it's working like /ns identify command as it should return an error that is not online.

For Example:

I connecting with "tester" nickname and i want to regain my nickname "main" that my head nickname is NOT currently online so i use
/ns regain main mypassword_here
Then it should reply an error that is not online instead of allowing the regain to proceed.

`/nick tester`
`/server .. .. `
`/ns regain main mypassword_here`
`Your nick is now main`
`main has been regained.`

- Thanks!

**Comment by grawity** [comment]
I think this is by-design – the REGAIN command's goal is to give you your nickname back, clearing any obstacles in the process. If there aren't any, it'll still give you your nickname back. (It's used in places like post-connect commands which have no capability for error checking.)

**Comment by alyx** [comment]
@grawity is correct, this is by design. Although technically it is not doing anything additional, this does still accomplish the goal of "give you your nickname back", so it is not specifically an error case.
