### ISSUE TITLE
Feature request: NickServ force identify

### ISSUE THREAD

**Issue by cooldude13233** [atheme/atheme#709]
Hi,

I wish some dev would make at least a contrib module that implements Anope style nickserv force identify for nicknames(/accounts)..!

**Comment by examknow** [comment]
Tbh, this issue probably belongs in the [atheme-contrib-modules](https://github.com/atheme/atheme-contrib-modules) repo.

**Comment by alyx** [comment]
I don't believe we have a specific policy for core vs contrib tbh. cc @ilbelkyr

**Comment by examknow** [comment]
I was mainly saying this since the user had said "at least a contrib module". I personally feel like it would belong in contrib just judging by what kinds of modules are already there but that's obviously not my place to say.

**Comment by ilbelkyr** [comment]
contrib or not, as previously discussed on IRC, there doesn't seem to be much (if any) legitimate use for this sort of command, especially considering the potential for *ab*use. If users can't get into their accounts, there's password reset commands to address that.
