### ISSUE TITLE
Underscore within hostname

### ISSUE THREAD

**Issue by DK99** [atheme/atheme#713]
Hi,

I recently tried to take a vhost. But it always answered with `The vhost provided is invalid.`.
I then realized that my nick contains an underscore and your check for invalid hostnames doesn't cover it.
I am not sure if this is the intended behavior? If not I am happy to create a pull request to fix this issue.

**Comment by aaronmdjones** [comment]
While underscores are legal in DNS, they are not legal in hostnames.

**Comment by DK99** [comment]
Well too bad. Thank you for the very quick response. I need to change my nick
