### ISSUE TITLE
cannot ungrant +O from self when +o

### ISSUE THREAD

**Issue by jesopo** [atheme/atheme#714]
I can understand why you would be able to grant but not ungrant +O on other people when you have +o (so you can't take it from people you didn't give it to) but being able to ungrant it from yourself seems reasonable.

**Comment by alyx** [comment]
Can you clarify when this situation occurs?

**Comment by jesopo** [comment]
i think i was under the impression that +o can **grant** +O to themself when i wrote this

**Comment by brunnre8** [comment]
The issue came up on freenode when I was granted +O on a channel but wasn't able to remove +O in favor of +o on my own account (I didn't want to get auto opped, but still retain the right to op myself when needed
