### ISSUE TITLE
add immediate ENFORCE to require SASL or `IDENTIFY <nick> <pass>` first

### ISSUE THREAD

**Issue by jesopo** [atheme/atheme#715]
given ENFORCE still provides a 30 second (at least, on freenode) window of impersonation, it would be nice if `SET ENFORCE` had an option to immediately kick people off a nickname if they're not already identified, so they'd be required to use SASL or `IDENTIFY` with an account name before changing to a nickname registered to the account.

i'd propose this via `SET ENFORCE ON|OFF|IMMEDIATE`

**Comment by aaronmdjones** [comment]
This is already possible, of sorts, via `SET ENFORCETIME 1`.
