### ISSUE TITLE
OperServ svs commands missing

### ISSUE THREAD

**Issue by mayur3940** [atheme/atheme#718]
Missing commands for server admin 
/msg operserv svsjoin nick #chan
/msg operserv svsnick oldnick newnick
Or sajoin commands for server admin
/sajoin nick #chan
/sanick oldnick newnick

**Comment by grawity** [comment]
> Missing commands for server admin
> /msg operserv svsjoin nick #chan
> /msg operserv svsnick oldnick newnick

As far as I know, those are deliberately not supported, as they're abused more often than not.

> Or sajoin commands for server admin
> /sajoin nick #chan
> /sanick oldnick newnick

Those are ircd commands, not services commands - i.e. they are not handled by Atheme in the first place.

**Comment by mayur3940** [comment]
Thanks for reply grawity,  ya i forget that sajoin is a ircd commands, with anope its working fine, can you please try to add? I have tried maximum services but there is no better services than atheme services. Atheme services 👍

**Comment by aaronmdjones** [comment]
Atheme IRC services will never support `SVSJOIN` and `SVSNICK` as user-accessible commands as they are too open to abuse.
