### ISSUE TITLE
avoiding leaking oper status in remote whois

### ISSUE THREAD

**Issue by jesopo** [atheme/atheme#728]
some networks are configured to not show oper status in whois and some ircds have differing umodes (think +o/+O) for different levels of privilege, and atheme remote whois unconfigurably giving `RPL_WHOISOPERATOR` ends up leaking information

**Comment by alyx** [comment]
Reposting here for visibility.

Per developer discussion, we agree that it may not always be ideal to leak oper status during a remote whois, however we feel the best course of action moving forward is a configurable option to strip the `RPL_WHOISOPERATOR` oper string from a remote whois.

**Comment by jesopo** [comment]
do we want a new `atheme.conf` bool for this or do we want to treat `operstring = "";` (empty string) as "don't send RPL_WHOISOPERATOR"

**Comment by alyx** [comment]
I think an additional config bool would make the most sense. @ilbelkyr any thoughts?

**Comment by alyx** [comment]
Closed by #733
