### ISSUE TITLE
ability to semi-freeze accounts, to e.g. prevent SET ACCOUNTNAME

### ISSUE THREAD

**Issue by jesopo** [atheme/atheme#729]
like a freeze but less harsh, allow a user to continue using an account but prevent them doing things typically deemed abusable (think account extban evasion)

**Comment by jlu5** [comment]
I think this is already covered by `/ns restrict`:

-NickServ- Help for RESTRICT:
-NickServ-  
-NickServ- RESTRICT allows operators to restrict what an account can and can not do.
-NickServ- It will currently block a user from grouping nicks, **changing account name**,
-NickServ- registering a channel, registering a group, requesting a vHost or
-NickServ- taking an OFFERed vHost.

**Comment by jesopo** [comment]
seems a touch heavy handed for the usecases I thought of, but I'll concede because my usecases were not great
