### ISSUE TITLE
priv to give immunity from being kicked in a closed channel

### ISSUE THREAD

**Issue by jesopo** [atheme/atheme#743]

**Comment by jesopo** [comment]
maybe it would just make sense to not kick (s)opers from closed channels, it doesn't really feel like something that needs fine-grained control like a priv

**Comment by jesopo** [comment]
perhaps chanserv could just avoid kicking you if it's already joined the channel to set the closed modes. if you're able to get in after that, chances are you're probably override and shouldn't be kicked

**Comment by ilbelkyr** [comment]
> perhaps chanserv could just avoid kicking you if it's already joined the channel to set the closed modes. if you're able to get in after that, chances are you're probably override and shouldn't be kicked

(looks like that's what we went with in #744)

**Comment by jillest** [comment]
Why does anyone need to be in a closed channel? Since it is locked down on ircd level, it is not like you can use this to kline bots that attempt to join.

**Comment by jesopo** [comment]
some IRCd don't let you change the topic, even with oper overrides, if you're not in the channel.
