### ISSUE TITLE
[FEATURE] add a dns pool manager

### ISSUE THREAD

**Issue by examknow** [atheme/atheme#766]
A module to allow management of a DNS pool like anope's [dns module](https://github.com/anope/anope/blob/master/modules/dns.cpp)

**Comment by alyx** [comment]
Can you clarify the value in this feature?

**Comment by aaronmdjones** [comment]
What exactly would this be used for, and why would it be better than e.g. setting up a local dnsmasq?

**Comment by examknow** [comment]
It allows dropping servers out of the DNS rotation if they go down or split off the network and allow quick management via an OperServ command (anope version [here](https://github.com/anope/anope/blob/master/modules/operserv/dns.cpp)).

**Comment by aaronmdjones** [comment]
Services was never intended to do this, and we will not be adding such a feature. Configuration of DNS and zones is well outside the scope of this software.
