### ISSUE TITLE
Need help sync services

### ISSUE THREAD

**Issue by Taxick** [atheme/atheme#772]
Hi :)

First, i want to say im at NOOB, but trying to lean

I'm trying to get inspircd and atheme to sync properly, but I get an error.

**INFO**

I'm running the last version of inspircd (3.90) and Atheme (7.2.11)

**My config inspircd -> links.confg:**

```
<link name="services.at.futurenode.dk"
      ipaddr="159.69.220.163"
      port="7005"
      allowmask="159.69.220.163"
      timeout="300"
      ssl="ssl_gnutls"
      bind="159.69.220.163"
      statshidden="no"
      hidden="no"
      sendpass="MYPASS"
      recvpass="MYPASS">
```

**Other config in inspircd.conf**

<bind address="159.69.220.163" port="7000" type="servers">
<bind address="159.69.220.163" port="7005" type="servers" ssl="GnuTLS">

<uline server="services.at.futurenode.dk" silent="yes">

```
Loading core modules ....................
[*] Loading module:     m_md5.so
[*] Loading module:     m_sha256.so
[*] Loading module:     m_alias.so
[*] Loading module:     m_allowinvite.so
[*] Loading module:     m_alltime.so
[*] Loading module:     m_banexception.so
[*] Loading module:     m_botmode.so
[*] Loading module:     m_chancreate.so
[*] Loading module:     m_chanlog.so
[*] Loading module:     m_check.so
[*] Loading module:     m_chghost.so
[*] Loading module:     m_chgident.so
[*] Loading module:     m_cloaking.so
[*] Loading module:     m_clones.so
[*] Loading module:     m_conn_join.so
[*] Loading module:     m_conn_umodes.so
[*] Loading module:     m_connflood.so
[*] Loading module:     m_customprefix.so
[*] Loading module:     m_globops.so
[*] Loading module:     m_helpop.so
[*] Loading module:     m_hidechans.so
[*] Loading module:     m_hideoper.so
[*] Loading module:     m_ident.so
[*] Loading module:     m_joinflood.so
[*] Loading module:     m_lockserv.so
[*] Loading module:     m_messageflood.so
[*] Loading module:     m_namesx.so
[*] Loading module:     m_nicklock.so
[*] Loading module:     m_ojoin.so
[*] Loading module:     m_operjoin.so
[*] Loading module:     m_opermotd.so
[*] Loading module:     m_password_hash.so
[*] Loading module:     m_sajoin.so
[*] Loading module:     m_sakick.so
[*] Loading module:     m_samode.so
[*] Loading module:     m_sanick.so
[*] Loading module:     m_sapart.so
[*] Loading module:     m_saquit.so
[*] Loading module:     m_satopic.so
[*] Loading module:     m_securelist.so
[*] Loading module:     m_services_account.so
[*] Loading module:     m_showfile.so
[*] Loading module:     m_ssl_gnutls.so
[*] Loading module:     m_sslinfo.so
[*] Loading module:     m_ssl_openssl.so
[*] Loading module:     m_svshold.so
[*] Loading module:     m_uhnames.so
[*] Loading module:     m_spanningtree.so
```

**Atheme.conf**

```
uplink "services.at.futurenode.dk" {
        // The server name of the ircd you're linking to goes above.

        // host
        // The hostname to connect to.
        host = "irc.futurenode.dk";

        // vhost
        // The source IP to connect from, used on machines with multiple interfaces.
        #vhost = "159.69.220.163";

        // send_password
        // The password sent for linking.
        send_password = "MYPASS";

        // receive_password
        // The password received for linking.
        receive_password = "MYPASS";

        // port
        // The port to connect to.
        port = 7005;
};
```

**Atheme startup**

ircd@s1:~/atheme/bin$ ./atheme-services
[2021-04-10 13:21:46] atheme 7.2.11 is starting up...
[2021-04-10 13:21:46] opensex: grammar version is 1.
[2021-04-10 13:21:46] corestorage: data schema version is 12.
[2021-04-10 13:21:46] groupserv: opensex data schema version is 4.
[2021-04-10 13:21:46] pid 21234
[2021-04-10 13:21:46] running in background mode from /home/ircd/atheme

**ERROR in atheme.log**

```
[2021-04-10 13:25:59] atheme 7.2.11 is starting up...
[2021-04-10 13:25:59] opensex: grammar version is 1.
[2021-04-10 13:25:59] corestorage: data schema version is 12.
[2021-04-10 13:25:59] groupserv: opensex data schema version is 4.
[2021-04-10 13:25:59] uplink_connect(): connecting to first entry services.at.futurenode.dk[irc.futurenode.dk]:7005.
[2021-04-10 13:25:59] pid 21308
[2021-04-10 13:25:59] running in background mode from /home/ircd/atheme
[2021-04-10 13:25:59] irc_handle_connect(): connection to uplink established
[2021-04-10 13:25:59] connection_close(): connection tcp connection: irc.futurenode.dk[5] closed due to error 111 (Connection refused)
```
Hope somone can help a NOOB!

Regards

Thomas

**Comment by aaronmdjones** [comment]
1) Atheme does not support linking over TLS; remove the `ssl="ssl_gnutls"` setting.
2) Your uplink name is probably incorrect; I very much doubt your IRCd is called `services.at.futurenode.dk`.
3) Since you're insisting on the IRCd side that the connection must be made from a specific address, you may as well tell Atheme to use that address (uncomment the `vhost` setting) and set `host` to the same IP address too:
    ```
    uplink "irc.futurenode.dk" {    // or whatever your IRCd server name is
        host = "159.69.220.163";
        vhost = "159.69.220.163";
        send_password = "MYPASS";
        receive_password = "MYPASS";
        port = 7005;
    };        
    ```
4) Ensure that you have told the IRCd that port 7005 is used for server linking, and is NOT using TLS:
    `<bind address="159.69.220.163" port="7005" type="servers">`

**Comment by Taxick** [comment]
Hi :)

Thanks for your reply.  Im still have some problems :(

**From "inspircd.conf"**

<bind address="159.69.220.163" port="7000" type="servers">
<bind address="159.69.220.163" port="7005" type="servers" ssl="GnuTLS">

**From inspircd ->  links.conf**

```
<link name="services.at.futurenode.dk"
      ipaddr="159.69.220.163"
      port="7000"
      allowmask="159.69.220.163"
      timeout="300"
      bind="159.69.220.163"
      statshidden="no"
      hidden="no"
      sendpass="MYPASS"
      recvpass="MYPASS">
```
**From  atheme.conf**

```
uplink "irc.futurenode.dk" {
        // The server name of the ircd you're linking to goes above.

        // host
        // The hostname to connect to.
        host = "159.69.220.163";

        //Vhost
        vhost = "159.69.220.163";

        // send_password
        // The password sent for linking.
        send_password = "MYPASS";

        // receive_password
        // The password received for linking.
        receive_password = "MYPASS";

        // port
        // The port to connect to.
        port = 7000;
};

```

**From atheme.log**

```
[2021-04-10 14:05:58] atheme 7.2.11 is starting up...
[2021-04-10 14:05:58] opensex: grammar version is 1.
[2021-04-10 14:05:58] corestorage: data schema version is 12.
[2021-04-10 14:05:58] groupserv: opensex data schema version is 4.
[2021-04-10 14:05:58] uplink_connect(): connecting to first entry irc.futurenode.dk[159.69.220.163]:7000.
[2021-04-10 14:05:58] pid 22035
[2021-04-10 14:05:58] running in background mode from /home/ircd/atheme
[2021-04-10 14:05:58] irc_handle_connect(): connection to uplink established
[2021-04-10 14:05:58] m_error(): error from server: Mismatched server name or password (check the other server's snomask output for details - e.g. user mode +s +Ll)
```

What can be wrong?

// Thomas

**Comment by aaronmdjones** [comment]
1) Have you set Atheme's `serverinfo { name = "services.at.futurenode.dk"; };` ?

    It needs to match IRCd's `<link name="...">`

2) Have you set IRCd's `<server name="irc.futurenode.dk">` ?

    It needs to match Atheme's `uplink "..." {`

**Comment by Taxick** [comment]
@aaronmdjones - Thanks for your reply... I got it to work! 

The server name did not match!

**Comment by Taxick** [comment]
Hi.

Sorry for opening this again, but I have one last question..


**Sat Apr 10 2021 15:44:15 LINK: Server connection to services.at.futurenode.dk is not using SSL (TLS). This is VERY INSECURE and will not be allowed in the next major version of InspIRCd.**
Sat Apr 10 2021 15:44:15 LINK: Bursting to ^Bservices.at.futurenode.dk^B (Authentication: plaintext password).
Sat Apr 10 2021 15:44:15 LINK: Finished bursting to ^Bservices.at.futurenode.dk^B.

How to fix this?

**Comment by aaronmdjones** [comment]
InspIRCd will not log such a message if you connect services over localhost -- by using 127.0.0.1 as the source and destination address.

**Comment by Taxick** [comment]
> InspIRCd will not log such a message if you connect services over localhost -- by using 127.0.0.1 as the source and destination address.

Hi @aaronmdjones 

Thanks for your reply :) Can you tell me where to change it?

Yes im a noob :(

**Comment by examknow** [comment]
> Can you tell me where to change it?

You’ll need to change it in both your inspircd link config and in the atheme uplink config.

**Comment by aaronmdjones** [comment]
NOTE: This assumes services is running on the same machine as IRCd, which is the case here.

Replace the value of the following settings in IRCd's `<link>` block with `127.0.0.1`:

- `ipaddr`
- `allowmask`
- `bind`

Replace the value of the following settings in IRCd's `<bind>` block with `127.0.0.1`:

- `address`

Replace the value of the following settings in Atheme's `uplink` block with `127.0.0.1`:

- `vhost`
- `host`

**Comment by Taxick** [comment]
Hi :)

Thanks a lot for your big help :) IM really appreciate it! Now there is no error about it

One last problem and then I will stop :)

Can I encrypt the oper password in the atheme.conf? Right now it shows as plaintext, and I want to hash someway

How can I do it?  Is there a command like /MKPASSWD ?

**Comment by aaronmdjones** [comment]
If you have any password crypto modules loaded, oper passwords MUST be encrypted with one of those modules. Since you're running 7.2, you'll need to build contrib modules (`./configure --enable-contrib`) and load the `contrib/ns_generatehash` module. This will provide an OperServ command called `GENERATEHASH`. You do not need to be identified to use it.

**Comment by Taxick** [comment]
> If you have any password crypto modules loaded, oper passwords MUST be encrypted with one of those modules. Since you're running 7.2, you'll need to build contrib modules (`./configure --enable-contrib`) and load the `contrib/ns_generatehash` module. This will provide an OperServ command called `GENERATEHASH`. You do not need to be identified to use it.

Hi :)

Thanks for your reply 👍 

I have reinstalled atheme with the command `./configure --enable-contrib

But there is no module called "contrib/ns_generatehash"

**Comment by aaronmdjones** [comment]
Apologies; the contrib module binds the command to NickServ, not OperServ.

**Comment by Taxick** [comment]
Hi @aaronmdjones 

It all work now, and I'm happy :)

Thanks a lot for your big help 👍 - I close this ticket now.
