### ISSUE TITLE
Impossible to complete user registration if email was changed

### ISSUE THREAD

**Issue by nbraud** [atheme/atheme#777]
### Reproduction steps

1. Start registering a new account
2. Do NOT confirm the email address (for instance you cannot receive the confirmation email)
3. Use `SET EMAIL` to change to a new address
4. Confirm the new address

### Expected behavior

Address is confirmed, registration is completed

### Actual behavior

Address is confirmed, registration isn't completed, and cannot be completed (outside of ops intervention)

**Comment by aaronmdjones** [comment]
I have already privately fixed this locally, due to a report from another user. However, the fix has not yet been reviewed or tested.

**Comment by nbraud** [comment]
@aaronmdjones Thanks  :D

**Comment by aaronmdjones** [comment]
(Fixed by #790)
