### ISSUE TITLE
[OperServ] Can't identify

### ISSUE THREAD

**Issue by rmbeer** [atheme/atheme#781]
Can't identify with "/msg operserv identify XXX" command, even if I'm logged in the account and administrator from ircd-seven.
Activating debug mode seems to have some internal reading problem like sscanf, that i guess is the read of input:

[2021-05-25 01:12:03] -> :42XAAAAAB PRIVMSG 00AAAAAAH :identify XXX
[2021-05-25 01:12:03] atheme_pbkdf2v2_parse_dbentry: sscanf(3) was unsuccessful
[2021-05-25 01:12:03] <- :00AAAAAAH NOTICE 42XAAAAAB :Invalid password.
[2021-05-25 01:12:03] OperServ KillerWasp/AAAAAAAAB:XXX!~XXX@XXX failed IDENTIFY (bad password)

packages and sources:
GIT Atheme from 18 Apr
ircd-seven-1.1.5
Linux 5.12.3-arch1-1 #1 SMP PREEMPT Wed, 12 May 2021 17:54:18 +0000 x86_64 (Last update in 2021-05-16T17:40:13+0000)

**Comment by aaronmdjones** [comment]
If you are using OperServ's `IDENTIFY` functionality (an additional requirement on top of being logged into services), then the `operator {}` block has to contain an *encrypted* password. You can use the OperServ `GENHASH` command to create an encrypted password:

```
MSG(OperServ): GENHASH hunter2
OperServ: Using crypto provider crypto/pbkdf2v2:
OperServ:   $z$65$64000$H9fMUf3+4V/BWKNN3HGnxfLfvzhNDI8KcaPKQKXtMek=$v34ZRaR7X8OseJbrvuSjNDZIW6HmegBz+dxELJ3KmhE=$yvw/WAf8HfiBMmqFGwy0EKRWTdb1Np22mzEBvKadzDM=
```

... and then configure it like so:

```
operator "your-services-account-name" {
    operclass = "whatever";
    password = "$z$65$64000$H9fMUf3+4V/BWKNN3HGnxfLfvzhNDI8KcaPKQKXtMek=$v34ZRaR7X8OseJbrvuSjNDZIW6HmegBz+dxELJ3KmhE=$yvw/WAf8HfiBMmqFGwy0EKRWTdb1Np22mzEBvKadzDM=";
};
```

**Comment by rmbeer** [comment]
Very thanks. I fixed the problem.
