### ISSUE TITLE
crontab script for atheme

### ISSUE THREAD

**Issue by gUfriL-Network** [atheme/atheme#788]
can you give me cron scripts for database backup
every 1 day can send services.db to email

**Comment by mattatobin** [comment]
You want them to create a specific cron script just for you? You can't write a script to shut down services, copy the db file, start services, zip and sendmail it for you?

Pretty sure each step can be easily scraped together from an internet search and put together. So, why would you expect this sort of very specific task of server administration to be the project's responsibility?

**Comment by grawity** [comment]
@mattatobin While you're ~technically not wrong~, I would really appreciate if you did not act like an asshole to other users, especially when trying to speak on behalf of the project. Thanks for not doing it again.

**Comment by aaronmdjones** [comment]
We already have the basis of a cron script; it is located in the `dist/` directory.
