### ISSUE TITLE
Inspircd 3 support?

### ISSUE THREAD

**Issue by ProgVal** [atheme/atheme#795]
Hi,

InspIRCd 3 support seems undocumented, while InspIRCd 2 is mentioned in the following places:

* https://github.com/atheme/atheme/blob/master/dist/atheme.conf.example#L116
* https://github.com/atheme/atheme/blob/master/doc/IRCD#L51

And InspIRCd is mentioned with no version here:

* https://atheme.org/ircd.html

So these three places should probably mention explicitly whether InspIRCd 3 is supported or not.

**Comment by mattatobin** [comment]
Does your inspricd have `spanningtree` enabled?

**Comment by ProgVal** [comment]
I wrote this issue before trying to link them. I did manage to link them since, but I opened this issue because I think it should be documented.
