### ISSUE TITLE
customisably long register/resetpass/sendpass/return tokens

### ISSUE THREAD

**Issue by jesopo** [atheme/atheme#800]
16 chars feels like it'd be fine for absolutely any reasonable usecase but it also feels strange that these are not customisable for paranoid people and I'm fairly sure a lot of these things are not reasonably throttled

https://github.com/atheme/atheme/blob/db13ae4262c94b65a6d254e6f9b09d8bfe03f79d/modules/nickserv/register.c#L181

https://github.com/atheme/atheme/blob/4fa0e03bd3ce2cb6041a339f308616580c5aac29/modules/nickserv/resetpass.c#L61

https://github.com/atheme/atheme/blob/db13ae4262c94b65a6d254e6f9b09d8bfe03f79d/modules/nickserv/sendpass.c#L168-L170

https://github.com/atheme/atheme/blob/4fa0e03bd3ce2cb6041a339f308616580c5aac29/modules/nickserv/sendpass_user.c#L110-L112

https://github.com/atheme/atheme/blob/4fa0e03bd3ce2cb6041a339f308616580c5aac29/modules/nickserv/return.c#L50

**Comment by aaronmdjones** [comment]
I will not do this for REGISTER verification tokens, because a lot of use cases involve people manually typing those out, and going beyond 16 is only going to be annoying.

**Comment by jesopo** [comment]
that was exactly the usecase I was interested in, to offer email verification URLs

**Comment by aaronmdjones** [comment]
VERIFY REGISTER does not require you to be logged in, so it can be executed without authentication over XMLRPC. It would simply be a matter of setting up a webserver script to act as the middleman, and changing the register email template to prefix the token with the URL.

**Comment by jesopo** [comment]
yes, and having a URL without DNSBLs on it is a prime candidate for brute forcing registration verification tokens

**Comment by aaronmdjones** [comment]
The random alphabet is 62 characters and the length of the token is 16, giving a search space of `62^16`. On average you will discover the correct value half way through your search, so assuming you can submit one trillion (`1,000,000,000,000`) requests per day, it will take you `6.53 * 10^13` years. You only have 24 hours.
