### ISSUE TITLE
Document that ChanServ CLOSE requires chan:admin privs

### ISSUE THREAD

**Issue by JustAnotherArchivist** [atheme/atheme#851]
As I discovered today, ChanServ's `CLOSE` command requires the chan:admin priv. This isn't mentioned in [the documentation](https://github.com/atheme/atheme/wiki/ChanServ%3ACLOSE) (unlike on other commands, e.g. [FDROP](https://github.com/atheme/atheme/wiki/ChanServ%3AFDROP)).

I'd've sent a PR, but it isn't possible to create PRs against GitHub wikis.

**Comment by aaronmdjones** [comment]
The wiki page has been edited; thank you.
