### ISSUE TITLE
/ns resetpass restricting access

### ISSUE THREAD

**Issue by ptaylor2** [atheme/atheme#852]
The nickserv:resetpass is not defined in the operblock the individual still have access to the /nickserv reset pass command. Removing the individual oepr priv user:admin is not a option since they would not allow them to access some of the botserv and hostserv commands. This may be a bug in the current version of atheme running under linux.

```
operclass "SOP" {
        privs {
                # [...]
                user:admin;
                # [...]
        };
};
```     

This comment edited by @aaronmdjones to fix formatting above and reflect that the necessary privilege has been granted.

**Comment by aaronmdjones** [comment]
You have granted them the `user:admin` privilege, which is the privilege necessary for NickServ's RESETPASS function:

https://github.com/atheme/atheme/blob/1f41a5d2b19067cb57c22fe1b38d7f8f71a21e2a/modules/nickserv/resetpass.c#L77-L84

There is no `user:resetpass` privilege.

**Comment by aaronmdjones** [comment]
If you want to further restrict command privileges, see also https://github.com/atheme/atheme/blob/1f41a5d2b19067cb57c22fe1b38d7f8f71a21e2a/dist/atheme.conf.example#L1583-L1593 and https://github.com/atheme/atheme/blob/1f41a5d2b19067cb57c22fe1b38d7f8f71a21e2a/doc/PRIVILEGES#L146-L183

**Comment by ptaylor2** [comment]
Please clarify what should this be if its only allowed by the service root Administrator?

**Comment by ptaylor2** [comment]
I am not sure what to change this to in order to restrict the operators from using resetpass sine about every module is using the common priv user:admin and its also tied to botserv and hostserv. How ever I need to lock this down due to possible abuse to Service Root Administrator only. Can you please provide me with some information on how to do  his? Sorry I do not any C code.

**Comment by aaronmdjones** [comment]
I've already provided the documentation above; none of it is related to C. It's all done in the configuration file.

An example would be

```
nickserv {
    access {
        "RESETPASS" = "user:resetpass";
    };
};

operclass "sra" {
    privs {
        # [...]
        user:resetpass;
    };
};
```

**Comment by aaronmdjones** [comment]
Also, ask yourself whether you even need the `RESETPASS` module loaded at all.

**Comment by ptaylor2** [comment]
Yes, reset password is required if the user forgot their email login information or have a issue logging in to there email address ito recover their nick password.

I  do not understand the solution that you provide user:admin is to common and needs to be changed in resetpass.c but I am not sure what to change this to?

.access         = PRIV_USER_ADMIN,

**Comment by aaronmdjones** [comment]
Resetting a user's password is an administrative action on that user. `user:admin` is the privilege specifically created for managing administrative actions on users. It is the correct value.

**Comment by ptaylor2** [comment]
What you told me above I do not underestand since by default the hostserv, botserv and other modules use the common priv PRIV_USER_ADMIN,. I am trying to figure out how to lock down the resetpass so only the SRA can use it. 


This is to common priv used in atheme

operclass "SOP" {
        privs {
                # [...]
                user:admin;
                # [...]
        };
};

How does this restrict the command to SRA please

nickserv {
    access {
        "RESETPASS" = "user:resetpass";
    };
};

operclass "sra" {
    privs {
        # [...]
        user:resetpass;
    };
};



Resetting a user's password is an administrative action on that user. user:admin is the privilege specifically created for managing administrative actions on users. It is the correct value.

**Comment by ptaylor2** [comment]
This not good it crashed the services

-OperServ- Module security/cmdperm loaded.
-
-irc.chatternet.org- from services.chatternet.org: Rehashing /home/ircd/atheme/etc/atheme.conf to complete module load by request of zero.
-irc.chatternet.org- from services.chatternet.org: conf_rehash(): rehashing
-
