### ISSUE TITLE
Hello, chanserv

### ISSUE THREAD

**Issue by kuwaity33** [atheme/atheme#871]
Concerning chanserv Not regulated for channels after registration?
Note that I did the following command in the configuration file
join_chans;
What is the reason for not entering the channel?
Thank you

**Comment by siniStar7boy** [comment]
Check that the channel's **GUARD** flag is enabled _(or set)_.

**Comment by kuwaity33** [comment]
Thank you siniStar7boy
The problem has been solved, some spaces after modification to the assembly file conf
Greetings to you
