### ISSUE TITLE
non-blocking hook

### ISSUE THREAD

**Issue by wpbirney** [atheme/atheme#877]
Is there a proper way to delegate long running tasks started from inside a hook (hook_add_channel_message) so that they do not block any other commands received during the long running task.

I could of course fire things off into a thread pool and let them run there, but was not sure of the thread safety of calls like msg()

**Comment by aaronmdjones** [comment]
Nothing in atheme is thread-safe; IRC relies upon complete in-order processing of messages, so there's very little to be gained in the way of doing anything using threads, and lots to screw up.

The only threaded code that atheme uses is located in libargon2 for password hashing.

The only way to do background work from a hook is to fork a subprocess and exit when you are done; waiting on that process to complete in the parent. See `modules/contrib/ns_mxcheck_async` for an example.
