### ISSUE TITLE
Notice to the user of failed logins should be configurable

### ISSUE THREAD

**Issue by nomis** [atheme/atheme#881]
While banning clients that repeatedly fail authentication are a decision for the network, affected users should be able to disable receiving login failure notifications:

> 20220924.log:17:29:38	--	SaslServ (SaslServ@services.libera.chat): <Unknown user on erbium.libera.chat (via SASL):85.249.174.160> failed to login to Simon. There has been 1 failed login attempt since your last successful login.
> 20220924.log:21:22:15	--	SaslServ (SaslServ@services.libera.chat): <Unknown user on erbium.libera.chat (via SASL):85.249.174.160> failed to login to Simon. There have been 2 failed login attempts since your last successful login.
> 20220925.log:09:56:11	--	SaslServ (SaslServ@services.libera.chat): <Unknown user on tantalum.libera.chat (via SASL):85.249.174.160> failed to login to Simon. There have been 3 failed login attempts since your last successful login.
> ...
> 20220925.log:13:59:30	--	SaslServ (SaslServ@services.libera.chat): <Unknown user on erbium.libera.chat (via SASL):85.249.174.160> failed to login to Simon. There have been 103 failed login attempts since your last successful login.
> 20220925.log:14:00:16	--	SaslServ (SaslServ@services.libera.chat): <Unknown user on erbium.libera.chat (via SASL):85.249.174.160> failed to login to Simon. There have been 104 failed login attempts since your last successful login.

**Comment by ilbelkyr** [comment]
(implemented in #884)
