### ISSUE TITLE
OperServ help

### ISSUE THREAD

**Issue by jokerkw** [atheme/atheme#903]
Hi,
Regarding operator and powers
has been added joker
from atheme.conf
=========
operator "joker" {
operclass = "ircop";
password = "xxxxxxxxxxx";
};
--------------------
When you log on to the server
The following message appears
OperServ- You are now identified to OperServ

/msg OperServ help

How do I add the international operator ,

operclass netadmin & Services Root Administrator & globop
Thanks

**Comment by alyx** [comment]
Most of those do not exist for Atheme.

[By default, Atheme defines two Services (OperServ) oper classes](https://github.com/atheme/atheme/blob/master/dist/atheme.conf.example#L2987-L3061): `ircop` and `sra`.  These two oper classes cover essentially everything a services oper can do. 

The `ircop` class covers most functionality related to managing user accounts, groups, channels, network moderation and services-integrated server maintenance (e.g. juping). 

[The `sra` class extends the `ircop` class](https://github.com/atheme/atheme/blob/master/dist/atheme.conf.example#L3031), allowing an `sra` class oper to do everything an `ircop` class oper can do, as well as allowing them to manage more privileged settings, such as bypassing some of Atheme's configuration-level restrictions and using Services to block certain users from opering. 

Most networks function fine on these privilege sets, but if your usecase needs more unique permission distribution, you can create custom operclasses with:

```
operclass "mycooloperclass" {
    privs {
        /* Whatever privs this class needs */
    }
}
```

---

It's also worth noting that generally `netadmin` and `globop` type oper classes are seen on the IRCd-side oper configurations, not Services-side. The IRCd-side oper class does not affect how Services views the user (and, if the specific Atheme operclass does not include `needoper`, the user does not need to be oper'd on the IRCd at all!). Similarly, your Services-side operclasses have no effect on how your IRCd views individual opers.
