### ISSUE TITLE
Please update protocol/inspircd to the 1205 (v3) protocol

### ISSUE THREAD

**Issue by SadieCat** [atheme/atheme#904]
The protocol/inspircd module is currently using the 1202 (v2) protocol. This works with v3 because of the v2 compatibility layer but when v4 is released at the end of the year it will no longer be able to link as the v2 compatibility layer has been removed. In order to work with v4 Atheme will need to migrate to the v3 (1205) protocol which works on v3 and will work on v4 through the compatibility layer.

There's a changelog between server versions [here](https://docs.inspircd.org/server/change-log/#1205-v3) and full documentation for each server message [here](https://docs.inspircd.org/server/messages/#messages).

**Comment by alyx** [comment]
I'm curious; assuming we were to keep a v2 support module available, would it not be better to update directly to v4, with v2 covering v2/v3 and v4 covering v4/(eventually)v5?

**Comment by SadieCat** [comment]
Theoretically you could do that but also:

- InspIRCd v2 is eol and has been for quite some time. Any users of it who ask for support are being told to upgrade.
- 
- The v4 (1206) protocol is currently work in progress and until v4 is released may get breaking changes at any time which might be a problem if you want your users to be able to upgrade on release.

**Comment by SadieCat** [comment]
Gently bumping this because we're hopefully going to ship in the next few months.

**Comment by X-Anonymous-Y** [comment]
The “InspIRCd Release Candidate 2” has now been published. I don't think there will be any new future additions. The bugs will be fixed and the final version will be released at the end of the month ( I really hope so :] ). Wouldn't you like to publish at least one "Atheme Release Candidate/Alpha/Develop" for testing? PLEASE PLEASE PLEASE

**Comment by bug** [comment]
Any progress on that? Currently atheme is incompatible with inspircd 4.

**Comment by chotaire** [comment]
InspIRCd v4.1.0 has been released and there is no support by Atheme Services yet. We all can't upgrade until there is, because we love Atheme too.

**Comment by dwfreed** [comment]
Patches welcome.

As far as I'm aware, nobody who currently maintains Atheme uses InspIRCd, and it is difficult to work on something you don't use. Furthermore, this is a volunteer project, and people work on what they want to work on when they have the time to work on it. Continuing to comment on this issue asking for updates, progress, or someone else to do it isn't helpful, and is likely to annoy the maintainers, discouraging them from working on Atheme.

If you're willing and able to do the work, please feel free to comment here saying that to avoid the potential for duplicated effort. Everyone else who isn't willing or able to do the work should quietly wait patiently for the work to be done.

**Comment by paigeadelethompson** [comment]
^_____^ looks like you just need to change this from 1202 to 1206:

**Comment by paigeadelethompson** [comment]
Managed to make some progress here, 

```
atheme_1  | [2024-10-29 00:13:08] irc_handle_connect(): connection to uplink established
atheme_1  | [2024-10-29 00:13:08] <- CAPAB START 1206
atheme_1  | [2024-10-29 00:13:08] <- CAPAB CAPABILITIES :PROTOCOL=1206
atheme_1  | [2024-10-29 00:13:08] <- CAPAB END
atheme_1  | [2024-10-29 00:13:08] <- SERVER services.netcrave.network changeme 0 10X :IRC Services
atheme_1  | [2024-10-29 00:13:08] -> CAPAB START 1206
atheme_1  | [2024-10-29 00:13:08] -> CAPAB MODULES :anticaps antisnoop banredirect callerid cban cloak=cloak-host=cloak%2Fdqg.a21.1hc7q1.hidden&cloak-v4=cloak%2F75h.gmn.gb37gr.hidden&cloak-v6=cloak%2Fspms13.6ktv.ntoj.dk5csn.hidden&domain-parts=3&ignore-case=no&method=full&prefix=cloak%2F&suffix=.hidden codepage=front=ABCDEFGHIJKLMNOPQRSTUVWXYZ%5B%5C%5D%5E_%60abcdefghijklmnopqrstuvwxyz%7B%7C%7D&map=Aa%2CBb%2CCc%2CDd%2CEe%2CFf%2CGg%2CHh%2CIi%2CJj%2CKk%2CLl%2CMm%2CNn%2COo%2CPp%2CQq%2CRr%2CSs%2CTt%2CUu%2CVv%2CWw%2CXx%2CYy%2CZz%2C&middle=-%2F0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ%5B%5C%5D%5E_%60abcdefghijklmnopqrstuvwxyz%7B%7C%7D dccallow defaulttopic filter=regex=glob globalload ircv3_ctctags kicknorejoin=max-time=60 repeat=actions=block%20kick%20kickban&max-backlog=20&max-diff=50&max-lines=20&max-secs=0 rline=regex=pcre services shun timedbans 
atheme_1  | [2024-10-29 00:13:08] -> CAPAB MODSUPPORT :account alltime asn autokick channelban check chghost=hostchars=%2C-.%2F0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz chgident chgname classban clearchan customtitle geoban globops ircv3_sts knock muteban nicklock nopartmsg noprivatemode opermotd realnameban remove sajoin sakick sanick sapart saquit serverban showwhois silence swhois teams uninvite 
atheme_1  | [2024-10-29 00:13:08] -> CAPAB CHANMODES :list:autoop=w list:ban=b list:banexception=e list:exemptchanops=X list:filter=g list:invex=I list:namebase=Z param-set:anticaps=B param-set:antisnoop=W param-set:delaymsg=d param-set:flood=f param-set:history=H param-set:joinflood=j param-set:kicknorejoin=J param-set:limit=l param-set:nickflood=F param-set:redirect=L param-set:repeat=E param:key=k prefix:1000000:operprefix=*y prefix:10000:voice=+v prefix:20000:halfop=%h prefix:30000:op=@o prefix:40000:admin=&a prefix:50000:founder=~q prefix:9000000:official-join=!Y simple:allowinvite=A simple:auditorium=u simple:blockcolor=c simple:blockhighlight=V simple:c_registered=r simple:censor=G simple:delayjoin=D simple:inviteonly=i simple:moderated=m simple:noctcp=C simple:noextmsg=n simple:nokick=Q simple:noknock=K simple:nonick=N simple:nonotice=T simple:operonly=O simple:permanent=P simple:private=p simple:reginvite=R simple:regmoderated=M simple:secret=s simple:sslonly=z simple:stripcolor=S simple:topiclock=t
atheme_1  | [2024-10-29 00:13:08] -> CAPAB USERMODES :param-set:snomask=s simple:antiredirect=L simple:bot=B simple:callerid=g simple:cloak=x simple:deaf=d simple:deaf_commonchan=c simple:helpop=h simple:hidechans=I simple:hideoper=H simple:invisible=i simple:nohistory=N simple:oper=o simple:override=O simple:privdeaf=D simple:regdeaf=R simple:servprotect=k simple:showwhois=W simple:sslqueries=z simple:u_censor=G simple:u_noctcp=T simple:u_registered=r simple:u_stripcolor=S simple:wallops=w
atheme_1  | [2024-10-29 00:13:08] -> CAPAB EXTBANS :acting:stripcolor=S matching:server=s matching:realname=r matching:realmask=a matching:opertype=O acting:partmsg=p matching:account=R matching:unauthed=U acting:blockinvite=A matching:country=G matching:asn=b matching:channel=j acting:nonotice=T acting:blockcolor=c acting:nonick=N matching:gateway=w matching:team=t matching:fingerprint=z matching:class=n acting:nokick=Q acting:mute=m matching:oper=o acting:noctcp=C
atheme_1  | [2024-10-29 00:13:08] -> CAPAB CAPABILITIES :CHALLENGE=bnb72AzXRngJv1fntotV CASEMAPPING=ascii MAXHOST=64 MAXCHANNEL=31 MAXKICK=256 EXTBANFORMAT=any MAXNICK=31 MAXMODES=32 MAXQUIT=256 MAXREAL=130 MAXUSER=16 MAXAWAY=256 MAXLINE=512 MAXTOPIC=256
atheme_1  | [2024-10-29 00:13:08] -> CAPAB END
atheme_1  | [2024-10-29 00:13:08] -> ERROR :Invalid format server ID: 0!
atheme_1  | [2024-10-29 00:13:08] m_error(): error from server: Invalid format server ID: 0!
atheme_1  | [2024-10-29 00:13:08] recvq_put(): fd 8 closed the connection
atheme_1  | [2024-10-29 00:13:08] uplink_close(): ----------------------- clearing -----------------------
atheme_1  | [2024-10-29 00:13:08] uplink_close(): ------------------------- done -------------------------
```

Unfortunately I can't see where that `m_error` is bailing out

**Comment by SadieCat** [comment]
@paigeadelethompson If you need any help with InspIRCd protocol stuff you can message me on Libera or ask in #inspircd.dev on Teranova (irc.teranova.net:+6697).

**Comment by SadieCat** [comment]
I have submitted PR #931 to do this. I'd appreciate help reviewing and testing.

**Comment by paigeadelethompson** [comment]
@SadieCat We ended up delaying the switch over of the network until we can figure out what sendq/recvq settings will work so I will check and see if atheme is of interest still (I'm sure it will be, but ideally we need to migrate accounts from anope and I have no idea how to go about that the password hashing would need to be the same I know that much at least. I'll check and see if we can manage
