### ISSUE TITLE
The vulnerability is a memory leak bug located at line 203 of the file /atheme/src/crypto-benchmark/main.c

### ISSUE THREAD

**Issue by LuMingYinDetect** [atheme/atheme#921]
Hello, I am a graduate student specializing in static analysis of programs. Recently, while using a static analysis tool to detect issues in open-source projects, I found several defects in the project. The description of the defects can be found at the following link:https://github.com/LuMingYinDetect/Atheme_defects/blob/main/Atheme_detect_1.md

**Comment by dwfreed** [comment]
It is a benchmarking tool, not a long-running process.  Additionally, if this leak is triggered, the process exits.  This is not a concern.

**Comment by yinluming13579** [comment]
> It is a benchmarking tool, not a long-running process. Additionally, if this leak is triggered, the process exits. This is not a concern.

Thank you for your reply!

**Comment by LuMingYinDetect** [comment]
> It is a benchmarking tool, not a long-running process. Additionally, if this leak is triggered, the process exits. This is not a concern.

Thank you for your reply!
