### ISSUE TITLE
assert.h:54:32: error: incompatible types when returning type _Bool but chanacs_t {aka struct chanacs_ } was expected

### ISSUE THREAD

**Issue by clinew** [atheme/atheme#932]
Taken from [Gentoo bug #944125](https://bugs.gentoo.org/show_bug.cgi?id=944125).

The relevant section of the log appears to be:

    CompileLib: armv7a-unknown-linux-gnueabihf-gcc -MMD -MP -fPIC -DPIC -I/usr/include/libmowgli-2 -O2 -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=hard -pipe -pipe -frecord-gcc-switches -fno-diagnostics-color -fmessage-length=0 -fPIC -DPIC  -I../include -c -o commandtree.lib.o commandtree.c
    In file included from /usr/include/libmowgli-2/mowgli.h:50,
                     from ../include/stdinc.h:13,
                     from ../include/atheme.h:19,
                     from account.c:24:
    account.c: In function `chanacs_open':
    /usr/include/libmowgli-2/core/assert.h:54:32: error: incompatible types when returning type `_Bool' but `chanacs_t *' {aka `struct chanacs_ *'} was expected
       54 |                         return (val); \
          |                                ^
    account.c:1782:9: note: in expansion of macro `return_val_if_fail'
     1782 |         return_val_if_fail(mychan != NULL, false);
          |         ^~~~~~~~~~~~~~~~~~
    /usr/include/libmowgli-2/core/assert.h:54:32: error: incompatible types when returning type `_Bool' but `chanacs_t *' {aka `struct chanacs_ *'} was expected
       54 |                         return (val); \
          |                                ^
    account.c:1783:9: note: in expansion of macro `return_val_if_fail'
     1783 |         return_val_if_fail((mt != NULL && hostmask == NULL) || (mt == NULL && hostmask != NULL), false);
          |         ^~~~~~~~~~~~~~~~~~
    CompileLib: armv7a-unknown-linux-gnueabihf-gcc -MMD -MP -fPIC -DPIC -I/usr/include/libmowgli-2 -O2 -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=hard -pipe -pipe -frecord-gcc-switches -fno-diagnostics-color -fmessage-length=0 -fPIC -DPIC  -I../include -c -o ctcp-common.lib.o ctcp-common.c
    make[1]: *** [../buildsys.mk:320: account.lib.o] Error 1
    make[1]: *** Waiting for unfinished jobs....
    make[1]: Leaving directory '/var/tmp/portage/net-irc/atheme-services-7.2.12-r4/work/atheme-services-v7.2.12/libathemecore'
    make: *** [buildsys.mk:120: libathemecore] Error 2

This appears to be due to the following lines of code: https://github.com/atheme/atheme/blob/v7.2.12/libathemecore/account.c#L1782 https://github.com/atheme/atheme/blob/v7.2.12/libathemecore/account.c#L1783 .  I suspect changing the second parameter from `false` to `NULL` will fix the compilation error.

**Comment by aaronmdjones** [comment]
See commit a0410c301293736a09b52763d25893019ede3e3a for the fix for the older version. Note that the 7.2 branch is not getting a new release unless there is a security issue to fix; so Gentoo will have to follow the git branch instead of the release tarball or carry the diff themselves.
